# =============================================================================
# Project: Frailty Trajectories Before and After Incident Cancer in the
#          Health Professionals Follow-up Study
# Script:  1.1_check_timebin_fda_support.R
# Author:  Nemo Zhou
# Date started:      2026-06-29
# Date last updated: 2026-07-17 (visual-data outputs moved; PNG writes removed)
#
# Purpose:
#   Diagnoses whether the current risk-set matched longitudinal frailty data
#   support a time-bin GLME event-study analysis and a complementary functional
#   data analysis (FDA) of frailty trajectories before and after incident cancer.
#
#   The script answers three pre-modeling questions:
#     1. Are there enough frailty-index observations in each relative-time bin
#        for cancer cases and matched cancer-free controls?
#     2. Do participant/assignment-level frailty histories have enough repeated
#        observations and relative-time coverage for FDA?
#     3. Are early and late relative-time tails or missing FI values likely to
#        force wider bins or a restricted FDA window?
#
#   Inputs:
#     Data/riskset_matched_analysis_long.rds
#       - Risk-set matched long data generated by 2.1.
#       - Contains one row per matched assignment-cycle FI observation.
#     Data/FI_longitudinal_1986_2020_IMPUTED_Cancer.rds
#       - Cleaned longitudinal FI data, used here only to recover death timing
#         and to evaluate missing FI in the same matched/indexed structure.
#
#   Outputs:
#     Results/cancer/data/1.1_timebin_support_by_cohort.csv
#     Results/cancer/data/1.1_timebin_support_overall.csv
#     Results/cancer/data/1.1_fda_repeated_measures_by_trajectory.csv
#     Results/cancer/data/1.1_fda_relative_time_coverage.csv
#     Results/cancer/data/1.1_fda_missing_fi_by_bin.csv
#     Results/cancer/data/1.1_fda_feasibility_summary.csv
#
# Notes:
#   Controls may be reused across case index times in the risk-set design. For
#   FDA support checks, this script therefore defines a trajectory assignment as
#   the unique combination of Cohort, match_set, participant id, and role. This
#   keeps each matched control's assigned index time distinct.
#
# Units:
#   index_date, worked_rtmnyr, dtdth, and dbmy09 are months since 1900.
#   Age_Centered is years relative to assigned index time.
# =============================================================================

library(dplyr)
library(tidyr)
library(ggplot2)


# -----------------------------------------------------------------------------
# 1. Paths, parameters, and required columns
# -----------------------------------------------------------------------------

project_dir <- "/Users/nemo/Library/CloudStorage/OneDrive-HarvardUniversity/Research/Frailty HPFS"
data_dir    <- file.path(project_dir, "Data")
results_dir <- file.path(project_dir, "Results", "cancer", "data")

matched_path <- file.path(data_dir, "riskset_matched_analysis_long.rds")
raw_path     <- file.path(data_dir, "FI_longitudinal_1986_2020_IMPUTED_Cancer.rds")

target_cycles <- c("88", "92", "96", "00", "04", "08", "12", "16", "20")

# Minimum counts used only for feasibility flags, not exclusions.
MIN_CASE_TRAJECTORIES_PER_BIN    <- 50
MIN_CONTROL_TRAJECTORIES_PER_BIN <- 250
MIN_TRAJECTORY_MEASURES_FOR_FDA  <- 4

required_matched_cols <- c(
  "id", "match_set", "index_date", "role", "Cohort", "cycle",
  "age_at_cycle", "fi_score_nocancer", "dbmy09", "index_age",
  "Age_Centered", "Group"
)

if (!file.exists(matched_path)) {
  stop(
    "Matched risk-set dataset not found at: ", matched_path,
    "\nRun Code/2_data_analysis/2.1_create_riskset_high_low_burden.R first to create it."
  )
}
if (!file.exists(raw_path)) {
  stop("Cleaned FI dataset not found at: ", raw_path)
}


# -----------------------------------------------------------------------------
# 2. Load data and define relative-time bins
# -----------------------------------------------------------------------------

matched_long <- readRDS(matched_path)
missing_cols <- setdiff(required_matched_cols, names(matched_long))
if (length(missing_cols) > 0) {
  stop("Matched dataset is missing required columns: ",
       paste(missing_cols, collapse = ", "))
}

raw_fi <- readRDS(raw_path)

inner_breaks <- seq(-16, 16, by = 2)
rel_breaks <- c(-Inf, inner_breaks, Inf)
rel_labels <- c(
  "<= -16 years",
  paste0(
    inner_breaks[-length(inner_breaks)],
    " to ",
    if_else(inner_breaks[-1] > 0,
            paste0("+", inner_breaks[-1]),
            as.character(inner_breaks[-1]))
  ),
  "> +16"
)

add_relative_time_bin <- function(data, rel_time_col = "Age_Centered") {
  data %>%
    mutate(
      rel_time_bin = cut(
        .data[[rel_time_col]],
        breaks = rel_breaks,
        labels = rel_labels,
        right = TRUE,
        include.lowest = TRUE
      )
    )
}

death_lookup <- raw_fi %>%
  mutate(
    id    = as.character(id),
    dtdth = as.numeric(dtdth)
  ) %>%
  group_by(id) %>%
  summarize(dtdth = suppressWarnings(max(dtdth, na.rm = TRUE)), .groups = "drop") %>%
  mutate(dtdth = if_else(is.infinite(dtdth), NA_real_, dtdth))

assignment_index <- matched_long %>%
  mutate(
    id         = as.character(id),
    match_set  = as.character(match_set),
    role       = as.character(role),
    Group      = as.character(Group),
    Cohort     = as.character(Cohort),
    index_date = as.numeric(index_date),
    dbmy09     = as.numeric(dbmy09),
    trajectory_id = paste(Cohort, match_set, id, role, sep = "__")
  ) %>%
  distinct(trajectory_id, Cohort, Group, id, match_set, role, index_date, dbmy09) %>%
  left_join(death_lookup, by = "id") %>%
  mutate(
    index_age = (index_date - dbmy09) / 12,
    death_rel_time = (dtdth - index_date) / 12
  )

raw_panel <- raw_fi %>%
  mutate(
    id                = as.character(id),
    cycle             = as.character(cycle),
    worked_rtmnyr     = as.numeric(worked_rtmnyr),
    dbmy09            = as.numeric(dbmy09),
    participated      = as.numeric(participated),
    fi_score_nocancer = as.numeric(fi_score_nocancer)
  ) %>%
  filter(
    participated == 1,
    cycle %in% target_cycles,
    !is.na(worked_rtmnyr),
    !is.na(dbmy09)
  ) %>%
  transmute(
    id,
    cycle,
    age_at_cycle = (worked_rtmnyr - dbmy09) / 12,
    fi_score_nocancer,
    fi_missing = is.na(fi_score_nocancer)
  )

matched_panel_for_missing <- assignment_index %>%
  inner_join(raw_panel, by = "id", relationship = "many-to-many") %>%
  mutate(Age_Centered = age_at_cycle - index_age) %>%
  add_relative_time_bin() %>%
  filter(!is.na(rel_time_bin))

matched_support <- matched_panel_for_missing %>%
  filter(!fi_missing)


# -----------------------------------------------------------------------------
# 3. Time-bin support table for event-study GLME
# -----------------------------------------------------------------------------

trajectory_bin_status <- matched_support %>%
  distinct(trajectory_id, Cohort, Group, rel_time_bin) %>%
  left_join(
    matched_support %>%
      group_by(trajectory_id) %>%
      summarize(
        max_rel_time    = max(Age_Centered, na.rm = TRUE),
        death_rel_time  = suppressWarnings(max(death_rel_time, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      mutate(death_rel_time = if_else(is.infinite(death_rel_time), NA_real_, death_rel_time)),
    by = "trajectory_id"
  ) %>%
  mutate(
    bin_upper = rel_breaks[match(as.character(rel_time_bin), rel_labels) + 1],
    has_later_fi_after_bin = if_else(is.infinite(bin_upper), FALSE, max_rel_time > bin_upper),
    died_after_bin_end = if_else(
      is.na(death_rel_time) | is.infinite(bin_upper),
      FALSE,
      death_rel_time > bin_upper
    ),
    no_later_fi_after_bin = !has_later_fi_after_bin,
    death_or_no_later_fi_after_bin = died_after_bin_end | no_later_fi_after_bin
  )

make_timebin_summary <- function(data, status_data, group_vars) {
  obs_summary <- data %>%
    group_by(across(all_of(group_vars)), rel_time_bin, .drop = FALSE) %>%
    summarize(
      cancer_case_trajectories_with_fi =
        n_distinct(trajectory_id[Group == "Cancer Case"]),
      cancer_case_observations_with_fi =
        sum(Group == "Cancer Case"),
      control_trajectory_assignments_with_fi =
        n_distinct(trajectory_id[Group == "Control"]),
      control_observations_with_fi =
        sum(Group == "Control"),
      mean_age = mean(age_at_cycle, na.rm = TRUE),
      median_age = median(age_at_cycle, na.rm = TRUE),
      .groups = "drop"
    )

  attrition_summary <- status_data %>%
    group_by(across(all_of(group_vars)), rel_time_bin, .drop = FALSE) %>%
    summarize(
      trajectories_with_no_later_fi_after_bin =
        sum(no_later_fi_after_bin, na.rm = TRUE),
      trajectories_died_after_bin_end =
        sum(died_after_bin_end, na.rm = TRUE),
      trajectories_died_or_no_later_fi_after_bin =
        sum(death_or_no_later_fi_after_bin, na.rm = TRUE),
      .groups = "drop"
    )

  obs_summary %>%
    left_join(attrition_summary, by = c(group_vars, "rel_time_bin")) %>%
    mutate(
      mean_age = if_else(is.nan(mean_age), NA_real_, mean_age),
      median_age = if_else(is.nan(median_age), NA_real_, median_age),
      case_bin_support_ok =
        cancer_case_trajectories_with_fi >= MIN_CASE_TRAJECTORIES_PER_BIN,
      control_bin_support_ok =
        control_trajectory_assignments_with_fi >= MIN_CONTROL_TRAJECTORIES_PER_BIN
    ) %>%
    arrange(across(all_of(group_vars)), rel_time_bin)
}

timebin_by_cohort <- make_timebin_summary(
  matched_support,
  trajectory_bin_status,
  group_vars = "Cohort"
)

timebin_overall <- make_timebin_summary(
  matched_support %>% mutate(Analysis = "All cohorts combined"),
  trajectory_bin_status %>% mutate(Analysis = "All cohorts combined"),
  group_vars = "Analysis"
)


# -----------------------------------------------------------------------------
# 4. FDA support checks: repeated measures and relative-time coverage
# -----------------------------------------------------------------------------

trajectory_measure_counts <- matched_support %>%
  group_by(Cohort, Group, trajectory_id) %>%
  summarize(
    id = first(id),
    n_fi_measurements = n_distinct(cycle),
    min_relative_time = min(Age_Centered, na.rm = TRUE),
    max_relative_time = max(Age_Centered, na.rm = TRUE),
    relative_time_span = max_relative_time - min_relative_time,
    .groups = "drop"
  )

fda_repeated_measures <- trajectory_measure_counts %>%
  group_by(Cohort, Group) %>%
  summarize(
    n_trajectory_assignments = n(),
    n_original_participants = n_distinct(id),
    mean_fi_measurements = mean(n_fi_measurements),
    median_fi_measurements = median(n_fi_measurements),
    p25_fi_measurements = as.numeric(quantile(n_fi_measurements, 0.25)),
    p75_fi_measurements = as.numeric(quantile(n_fi_measurements, 0.75)),
    min_fi_measurements = min(n_fi_measurements),
    max_fi_measurements = max(n_fi_measurements),
    pct_with_at_least_4_fi =
      mean(n_fi_measurements >= MIN_TRAJECTORY_MEASURES_FOR_FDA) * 100,
    mean_relative_time_span = mean(relative_time_span, na.rm = TRUE),
    median_relative_time_span = median(relative_time_span, na.rm = TRUE),
    .groups = "drop"
  )

fda_relative_time_coverage <- matched_support %>%
  mutate(relative_year = round(Age_Centered)) %>%
  filter(relative_year >= -20, relative_year <= 20) %>%
  group_by(Cohort, Group, relative_year) %>%
  summarize(
    trajectory_assignments_with_fi = n_distinct(trajectory_id),
    original_participants_with_fi = n_distinct(id),
    fi_observations = n(),
    mean_fi = mean(fi_score_nocancer, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  arrange(Cohort, Group, relative_year)


# -----------------------------------------------------------------------------
# 5. Missing FI by relative-time bin in the matched/indexed structure
# -----------------------------------------------------------------------------

fda_missing_fi_by_bin <- matched_panel_for_missing %>%
  group_by(Cohort, Group, rel_time_bin, .drop = FALSE) %>%
  summarize(
    indexed_panel_rows = n(),
    missing_fi_rows = sum(fi_missing),
    observed_fi_rows = sum(!fi_missing),
    pct_missing_fi = missing_fi_rows / indexed_panel_rows * 100,
    trajectory_assignments = n_distinct(trajectory_id),
    .groups = "drop"
  ) %>%
  arrange(Cohort, Group, rel_time_bin)


# -----------------------------------------------------------------------------
# 6. FDA feasibility summary
# -----------------------------------------------------------------------------

feasible_bins <- timebin_overall %>%
  filter(case_bin_support_ok, control_bin_support_ok)

suggested_window <- if (nrow(feasible_bins) == 0) {
  "No 2-year relative-time bins met both case and control support thresholds."
} else if (nrow(feasible_bins) == length(rel_labels)) {
  "All prespecified bins met support thresholds, including <= -16 years and > +16 years"
} else {
  paste(
    "Supported bins:",
    paste(as.character(feasible_bins$rel_time_bin), collapse = ", ")
  )
}

fda_feasibility_summary <- tibble::tibble(
  FDA_requirement = c(
    "Repeated measures per trajectory assignment",
    "Coverage of relative time",
    "Sparse tails",
    "Irregular measurement",
    "Missing FI"
  ),
  What_was_examined = c(
    paste0("Distribution of observed FI measurements per trajectory assignment; threshold = ",
           MIN_TRAJECTORY_MEASURES_FOR_FDA, "+ FI measurements"),
    "Counts of trajectory assignments and original participants by rounded relative year and by 2-year bin",
    paste0("2-year bins with fewer than ", MIN_CASE_TRAJECTORIES_PER_BIN,
           " cancer-case trajectories or fewer than ",
           MIN_CONTROL_TRAJECTORIES_PER_BIN, " control trajectory assignments"),
    "Questionnaire-cycle observations indexed to each case/control assigned index time",
    "Missing no-cancer FI among participated target-cycle rows after applying each assigned index time"
  ),
  Output_file = c(
    "1.1_fda_repeated_measures_by_trajectory.csv",
    "1.1_fda_relative_time_coverage.csv and 1.1_timebin_support_*.csv",
    "1.1_timebin_support_*.csv",
    "1.1_fda_relative_time_coverage.csv",
    "1.1_fda_missing_fi_by_bin.csv"
  ),
  Initial_interpretation = c(
    paste0(
      round(
        min(fda_repeated_measures$pct_with_at_least_4_fi, na.rm = TRUE),
        1
      ),
      "% or more trajectory assignments within every cohort/group have at least ",
      MIN_TRAJECTORY_MEASURES_FOR_FDA, " observed FI measurements."
    ),
    "Use the coverage table/plot to choose a common relative-time window with adequate case and control support.",
    paste0("Suggested supported window: ", suggested_window, "."),
    "HPFS FI is observed on questionnaire cycles, so FDA methods should allow sparse and irregular longitudinal curves.",
    "Use bin-specific missingness to assess whether missing FI is concentrated near diagnosis, after diagnosis, or near sparse tails."
  )
)


# -----------------------------------------------------------------------------
# 7. Plots
# -----------------------------------------------------------------------------

plot_counts <- matched_support %>%
  group_by(Cohort, Group, rel_time_bin) %>%
  summarize(trajectory_assignments_with_fi = n_distinct(trajectory_id), .groups = "drop")

p_timebin <- ggplot(
  plot_counts,
  aes(x = rel_time_bin, y = trajectory_assignments_with_fi, fill = Group)
) +
  geom_col(position = position_dodge(width = 0.8), width = 0.7) +
  facet_wrap(~ Cohort, scales = "free_y") +
  scale_fill_manual(values = c("Control" = "#2c7fb8", "Cancer Case" = "#d95f0e")) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 35, hjust = 1),
    panel.grid.minor = element_blank()
  ) +
  labs(
    title = "Observed FI Support by Relative-Time Bin",
    x = "Years relative to assigned index time",
    y = "Trajectory assignments with observed FI",
    fill = NULL
  )

p_coverage <- ggplot(
  fda_relative_time_coverage,
  aes(x = relative_year, y = trajectory_assignments_with_fi, color = Group)
) +
  geom_line(linewidth = 0.9) +
  geom_point(size = 1.5) +
  facet_wrap(~ Cohort, scales = "free_y") +
  scale_color_manual(values = c("Control" = "#2c7fb8", "Cancer Case" = "#d95f0e")) +
  theme_minimal(base_size = 12) +
  theme(legend.position = "bottom", panel.grid.minor = element_blank()) +
  labs(
    title = "FDA Relative-Time Coverage",
    x = "Rounded years relative to assigned index time",
    y = "Trajectory assignments with observed FI",
    color = NULL
  )

p_measure_counts <- ggplot(
  trajectory_measure_counts,
  aes(x = n_fi_measurements, fill = Group)
) +
  geom_histogram(binwidth = 1, position = "dodge", color = "white") +
  facet_wrap(~ Cohort, scales = "free_y") +
  scale_fill_manual(values = c("Control" = "#2c7fb8", "Cancer Case" = "#d95f0e")) +
  theme_minimal(base_size = 12) +
  theme(legend.position = "bottom", panel.grid.minor = element_blank()) +
  scale_x_continuous(breaks = seq(0, max(trajectory_measure_counts$n_fi_measurements), by = 1)) +
  labs(
    title = "Observed FI Measurements per Trajectory Assignment",
    x = "Number of FI measurements",
    y = "Trajectory assignments",
    fill = NULL
  )


# -----------------------------------------------------------------------------
# 8. Save outputs
# -----------------------------------------------------------------------------

write.csv(
  timebin_by_cohort,
  file.path(results_dir, "1.1_timebin_support_by_cohort.csv"),
  row.names = FALSE
)
write.csv(
  timebin_overall,
  file.path(results_dir, "1.1_timebin_support_overall.csv"),
  row.names = FALSE
)
write.csv(
  fda_repeated_measures,
  file.path(results_dir, "1.1_fda_repeated_measures_by_trajectory.csv"),
  row.names = FALSE
)
write.csv(
  fda_relative_time_coverage,
  file.path(results_dir, "1.1_fda_relative_time_coverage.csv"),
  row.names = FALSE
)
write.csv(
  fda_missing_fi_by_bin,
  file.path(results_dir, "1.1_fda_missing_fi_by_bin.csv"),
  row.names = FALSE
)
write.csv(
  fda_feasibility_summary,
  file.path(results_dir, "1.1_fda_feasibility_summary.csv"),
  row.names = FALSE
)

cat("\nTime-bin and FDA support diagnostics complete.\n")
cat("Main outputs saved to: ", results_dir, "\n", sep = "")
cat("\nOverall time-bin support:\n")
print(timebin_overall)
cat("\nFDA repeated-measures support:\n")
print(fda_repeated_measures)
cat("\nFDA feasibility summary:\n")
print(fda_feasibility_summary)
