# =============================================================================
# Project: Frailty Trajectories Before and After Incident Cancer in the
#          Health Professionals Follow-up Study
# Script:  10.0_GLME_cancer_free_functions.R
# Author:  Nemo Zhou
# Date started:      2026-07-19
# Date last updated: 2026-07-19
#
# Purpose:
#   Self-contained copy of the active 4.0 GLME event-study and natural-spline
#   Gaussian LME engine for the cancer-free-through-full-HPFS-endpoint
#   high/low-burden cohort generated by 9.1. It preserves the 4.0 model
#   specifications, convergence ladder, CR2/CR0/model-based covariance handling,
#   diagnostics, predictions, contrasts, and output tables while validating
#   the additional 9.xx matching provenance before fitting.
#
#   This file is intentionally separate from 4.0 so the existing GLME workflow
#   and outputs remain unchanged.
#
# Units:
#   Age_Centered is years relative to each person's attained age at the
#   assigned index. Outcome is fi_score_nocancer.
# =============================================================================

library(dplyr)
library(ggplot2)
library(lme4)
library(splines)

# A GLME run is valid only when its matched input has passed the matching
# engine's Gate G4 and the provenance record still hashes the exact RDS being
# fitted.  This check is shared by the subgroup wrappers (4.1-4.4) as well as
# the overall wrapper; it prevents silently fitting stale pre-repair cohorts.
validate_matching_provenance <- function(matched_path) {
  if (!file.exists(matched_path)) {
    stop("Matched dataset not found at ", matched_path, call. = FALSE)
  }
  project_dir <- dirname(dirname(normalizePath(matched_path, mustWork = FALSE)))
  diagnostics_dir <- file.path(project_dir, "Results", "cancer", "data",
                                "matching_diagnostics")
  output_stem <- tools::file_path_sans_ext(basename(matched_path))
  gate_path <- file.path(diagnostics_dir, paste0(output_stem, "_gate_g4.csv"))
  run_path <- file.path(diagnostics_dir, paste0(output_stem, "_run_metadata.rds"))
  if (!file.exists(gate_path) || !file.exists(run_path)) {
    stop("Gate G4 or matching provenance is missing for ", output_stem,
         ". Rerun the corresponding matching builder before fitting GLME.",
         call. = FALSE)
  }
  gate <- tryCatch(read.csv(gate_path, stringsAsFactors = FALSE),
                   error = function(e) {
                     stop("Could not read matching Gate G4 file ", gate_path,
                          ": ", conditionMessage(e), call. = FALSE)
                   })
  if (!("gate_pass" %in% names(gate)) ||
      !all(as.logical(gate$gate_pass) %in% TRUE)) {
    stop("Gate G4 did not pass for ", output_stem,
         ". Refusing to fit the matched GLME input.", call. = FALSE)
  }
  run_metadata <- readRDS(run_path)
  required_endpoint_fields <- c(
    "control_cancer_free_rule",
    "control_cancer_free_cutoff",
    "control_cancer_free_cutoff_units"
  )
  missing_endpoint_fields <- required_endpoint_fields[
    !required_endpoint_fields %in% names(run_metadata)
  ]
  if (length(missing_endpoint_fields) > 0L ||
      !identical(
        as.character(run_metadata$control_cancer_free_rule[[1]]),
        "through_full_hpfs_endpoint"
      ) ||
      !is.finite(as.numeric(run_metadata$control_cancer_free_cutoff[[1]])) ||
      !identical(
        as.character(run_metadata$control_cancer_free_cutoff_units[[1]]),
        "months_since_1900"
      )) {
    stop(
      "Matching provenance is not the 9.xx full-HPFS-endpoint cancer-free design ",
      "for ", output_stem, ". Refusing to fit this cohort.",
      call. = FALSE
    )
  }
  expected_md5 <- if (!is.null(run_metadata$output_md5)) {
    unname(as.character(run_metadata$output_md5))
  } else {
    character(0)
  }
  observed_md5 <- unname(tools::md5sum(matched_path))
  if (length(expected_md5) != 1L || !nzchar(expected_md5) ||
      !identical(expected_md5, observed_md5)) {
    stop("Matched RDS hash does not match its Gate G4 provenance for ",
         output_stem, ". Rerun the matching builder.", call. = FALSE)
  }
  list(output_stem = output_stem, gate = gate, run_metadata = run_metadata,
       gate_path = gate_path, run_path = run_path, input_md5 = observed_md5)
}

# Active GLME event-study bin breaks -------------------------------------------
.es_inner_breaks <- seq(-20, 20, by = 2)
.es_rel_breaks   <- c(-Inf, .es_inner_breaks, Inf)
.es_rel_labels   <- c(
  "<= -20 years",
  paste0(
    .es_inner_breaks[-length(.es_inner_breaks)],
    " to ",
    if_else(.es_inner_breaks[-1] > 0,
            paste0("+", .es_inner_breaks[-1]),
            as.character(.es_inner_breaks[-1]))
  ),
  "> +20"
)
.es_ref_label <- "-2 to 0"

# Numeric midpoint for each bin label, for plotting on a relative-time axis.
.es_bin_midpoints <- setNames(
  c(min(.es_inner_breaks) - 1,
    head(.es_inner_breaks, -1) + 1,
    max(.es_inner_breaks) + 1),
  .es_rel_labels
)

add_relative_time_bin <- function(data, rel_time_col = "Age_Centered",
                                  ref_label = .es_ref_label) {
  data %>%
    mutate(
      rel_time_bin = cut(
        .data[[rel_time_col]],
        breaks = .es_rel_breaks,
        labels = .es_rel_labels,
        right = TRUE,
        include.lowest = TRUE
      ),
      rel_time_bin = factor(rel_time_bin, levels = .es_rel_labels)
    )
}

continuous_support_window <- function(support, window_yrs) {
  support <- support %>% arrange(match(as.character(rel_time_bin), .es_rel_labels))
  ref_i <- match(.es_ref_label, as.character(support$rel_time_bin))
  if (is.na(ref_i) || !support$support_ok[[ref_i]]) return(c(NA_real_, NA_real_))
  left_i <- ref_i
  right_i <- ref_i
  while (left_i > 1 && support$support_ok[[left_i - 1]]) left_i <- left_i - 1
  while (right_i < nrow(support) && support$support_ok[[right_i + 1]]) right_i <- right_i + 1
  left_break_i <- match(as.character(support$rel_time_bin[[left_i]]), .es_rel_labels)
  right_break_i <- match(as.character(support$rel_time_bin[[right_i]]), .es_rel_labels)
  lo <- max(-window_yrs, .es_rel_breaks[[left_break_i]])
  hi <- min(window_yrs, .es_rel_breaks[[right_break_i + 1]])
  c(lo, hi)
}

# Cluster-robust covariance for the primary participant-level inference. -------
# Cluster-robust covariance for the fixed effects, clustered on participant id.
# NOTE: clubSandwich requires the model's random-effect grouping to be nested
# within the clustering variable. Risk-set matching reuses a participant across
# match_sets, so id is NOT nested within match_set (they are crossed) and CR on
# match_set is rejected. Clustering on id pools every row a person contributes
# across assignments and addresses reuse/within-person dependence. It does not
# absorb residual dependence between different people in the same matched set;
# M3 assesses that separately with a matched-set random intercept.
get_primary_vcov <- function(model, cluster, cluster_name = "id") {
  fe <- names(lme4::fixef(model))
  if (requireNamespace("clubSandwich", quietly = TRUE)) {
    for (cr_type in c("CR2", "CR0")) {
      out_cs <- tryCatch(
        clubSandwich::vcovCR(model, cluster = cluster, type = cr_type),
        error = function(e) NULL
      )
      if (!is.null(out_cs)) {
        out <- as.matrix(out_cs)
        robust_ok <- nrow(out) == length(fe) && ncol(out) == length(fe) &&
          all(is.finite(out)) && isTRUE(all.equal(out, t(out), tolerance = 1e-8))
        if (robust_ok) {
          # Validate the downstream operations used by this analysis, not only
          # vcovCR construction. A crossed M3 covariance can be constructed but
          # still fail coefficient or small-sample Wald inference.
          robust_ok <- tryCatch({
            clubSandwich::coef_test(model, vcov = out_cs, test = "Satterthwaite")
            probe <- matrix(0, nrow = 1, ncol = length(fe))
            probe[1, 1] <- 1
            clubSandwich::Wald_test(model, constraints = probe, vcov = out_cs,
                                    test = "HTZ")
            TRUE
          }, error = function(e) FALSE)
        }
        if (robust_ok) {
          dimnames(out) <- list(fe, fe)
          return(list(V = out, V_cs = out_cs, robust = TRUE,
                      type = paste0(cr_type, " (cluster-robust on ", cluster_name, ")")))
        }
      }
    }
  }
  out <- as.matrix(vcov(model))
  dimnames(out) <- list(fe, fe)
  list(V = out, V_cs = NULL, robust = FALSE, type = "model-based")
}

coef_table_with_vcov <- function(model, Vobj) {
  if (!is.null(Vobj$V_cs)) {
    ct <- as.data.frame(clubSandwich::coef_test(model, vcov = Vobj$V_cs,
                                                test = "Satterthwaite"))
  } else {
    beta <- lme4::fixef(model)
    se <- sqrt(diag(Vobj$V))
    ct <- data.frame(Coef. = names(beta), Estimate = unname(beta), SE = se,
                     `d.f. (Satt)` = Inf, `p-val (Satt)` = 2 * pnorm(-abs(beta / se)),
                     check.names = FALSE)
  }
  names(ct)[names(ct) %in% c("Coef.", "Coef")] <- "Term"
  names(ct)[names(ct) %in% c("Estimate", "beta")] <- "Estimate"
  names(ct)[names(ct) %in% c("d.f. (Satt)", "df_Satt")] <- "df"
  names(ct)[names(ct) %in% c("p-val (Satt)", "p_Satt")] <- "p_value"
  ct %>% transmute(
    Term, Estimate, SE, df = as.numeric(df), p_value = as.numeric(p_value),
    CI_low = Estimate - qt(0.975, df = df) * SE,
    CI_high = Estimate + qt(0.975, df = df) * SE,
    infer_method = if (Vobj$robust) paste(Vobj$type, "Satterthwaite") else "model-based normal"
  )
}

wald_with_vcov <- function(model, Vobj, constraints, label) {
  if (!is.null(Vobj$V_cs)) {
    ans <- as.data.frame(clubSandwich::Wald_test(
      model, constraints = constraints, vcov = Vobj$V_cs, test = "HTZ"
    ))
    return(ans %>% transmute(
      Test = label, Fstat, df_num, df_denom, p_value = p_val,
      infer_method = paste(Vobj$type, "HTZ")
    ))
  }
  beta <- lme4::fixef(model)
  est <- as.vector(constraints %*% beta)
  VV <- constraints %*% Vobj$V %*% t(constraints)
  q <- qr(VV)$rank
  chisq <- as.numeric(t(est) %*% MASS::ginv(VV) %*% est)
  data.frame(Test = label, Fstat = chisq / q, df_num = q,
             df_denom = Inf, p_value = pchisq(chisq, q, lower.tail = FALSE),
             infer_method = "model-based Wald chi-square")
}

# Joint Wald test that a named subset of fixed-effect coefficients are all 0. ---
joint_wald <- function(model, Vobj, terms, label) {
  beta <- lme4::fixef(model)
  terms <- intersect(terms, names(beta))
  if (length(terms) == 0) {
    return(data.frame(Test = label, Fstat = NA_real_, df_num = 0,
                      df_denom = NA_real_, p_value = NA_real_,
                      infer_method = Vobj$type))
  }
  constraints <- diag(length(beta))[match(terms, names(beta)), , drop = FALSE]
  wald_with_vcov(model, Vobj, constraints, label)
}

# Event-study interaction terms (Group x rel_time_bin), order-agnostic. --------
# Bin labels contain no ":", "rel_time_bin", or "GroupCancer Case" substrings,
# so stripping those tokens from a coefficient name returns the bin label.
.es_interaction_terms <- function(beta_names) {
  it <- beta_names[grepl(":", beta_names) &
                   grepl("rel_time_bin", beta_names) &
                   grepl("GroupCancer Case", beta_names)]
  data.frame(
    term = it,
    bin  = gsub("GroupCancer Case|rel_time_bin|:", "", it),
    stringsAsFactors = FALSE
  )
}

# Build a per-cohort prediction grid with covariates held at reference levels. --
.primary_covars <- c("index_age_z", "base_race", "base_marital", "base_living")
.full_extra_covars <- c("base_pckgr", "base_calor", "base_sat",
                        "base_diet_chol", "base_alco")
.full_covars <- c(.primary_covars, .full_extra_covars)

.spline_model_specs <- list(
  M0_raw = list(
    label = "M0 raw",
    role = "Minimally adjusted matched contrast",
    covars = "index_age_z",
    random = "(1 + Age_Centered | id)"
  ),
  M1_primary = list(
    label = "M1 primary",
    role = "Primary adjusted model",
    covars = .primary_covars,
    random = "(1 + Age_Centered | id)"
  ),
  M2_full = list(
    label = "M2 full",
    role = "Expanded baseline-covariate model",
    covars = .full_covars,
    random = "(1 + Age_Centered | id)"
  ),
  M3_primary_matching = list(
    label = "M3 primary + matching_id",
    role = "Primary model plus matched-set random intercept",
    covars = .primary_covars,
    random = "(1 + Age_Centered | id) + (1 | matching_id)"
  )
)

.make_ref_grid <- function(d, covars = .primary_covars, ...) {
  base_cols <- list()
  for (cv in covars) {
    if (cv == "index_age_z") {
      base_cols[[cv]] <- 0
    } else if (is.factor(d[[cv]])) {
      base_cols[[cv]] <- factor(levels(d[[cv]])[1], levels = levels(d[[cv]]))
    } else if (is.numeric(d[[cv]])) {
      base_cols[[cv]] <- mean(d[[cv]], na.rm = TRUE)
    } else {
      base_cols[[cv]] <- d[[cv]][which(!is.na(d[[cv]]))[1]]
    }
  }
  expand.grid(..., stringsAsFactors = FALSE) %>%
    mutate(!!!base_cols)
}

.fixed_rhs <- function(spline_terms = NULL, covars = .primary_covars,
                       time_term = "rel_time_bin") {
  group_time <- if (is.null(spline_terms)) {
    paste0("Group * ", time_term)
  } else {
    paste0("Group * (", paste(spline_terms, collapse = " + "), ")")
  }
  as.formula(paste("~", paste(c(group_time, covars), collapse = " + ")))
}

# Center and scale numeric model columns without changing the fitted model
# space.  Scaling is estimated on the exact model-specific complete-case
# fitting data and must subsequently be applied to its prediction grids.
.scale_model_numeric_columns <- function(data, columns) {
  columns <- intersect(columns, names(data))
  if (!length(columns)) {
    return(list(data = data,
                parameters = data.frame(column = character(), center = numeric(),
                                        scale = numeric(), stringsAsFactors = FALSE)))
  }
  if (!all(vapply(data[columns], is.numeric, logical(1)))) {
    stop("Only numeric columns may be standardized for model fitting.", call. = FALSE)
  }
  centers <- vapply(data[columns], mean, numeric(1), na.rm = TRUE)
  scales <- vapply(data[columns], stats::sd, numeric(1), na.rm = TRUE)
  if (any(!is.finite(centers)) || any(!is.finite(scales)) || any(scales <= 0)) {
    bad <- columns[!is.finite(centers) | !is.finite(scales) | scales <= 0]
    stop("Cannot standardize non-varying or non-finite model columns: ",
         paste(bad, collapse = ", "), call. = FALSE)
  }
  data[columns] <- Map(function(x, center, scale) (x - center) / scale,
                       data[columns], centers, scales)
  list(data = data,
       parameters = data.frame(column = columns, center = unname(centers),
                               scale = unname(scales), stringsAsFactors = FALSE))
}

.apply_model_scaling <- function(data, parameters) {
  if (!nrow(parameters)) return(data)
  missing_cols <- setdiff(parameters$column, names(data))
  if (length(missing_cols)) {
    stop("Prediction grid is missing scaled model columns: ",
         paste(missing_cols, collapse = ", "), call. = FALSE)
  }
  for (i in seq_len(nrow(parameters))) {
    column <- parameters$column[[i]]
    data[[column]] <- (data[[column]] - parameters$center[[i]]) /
      parameters$scale[[i]]
  }
  data
}

.assess_lmer_fit <- function(fit, allow_singular = FALSE, gradient_tol = 0.002) {
  opt_code <- fit@optinfo$conv$opt
  opt_code <- if (length(opt_code) == 0 || is.null(opt_code)) 0L else as.integer(opt_code[[1]])
  conv_messages <- fit@optinfo$conv$lme4$messages
  substantive_messages <- conv_messages
  if (allow_singular && length(substantive_messages)) {
    substantive_messages <- substantive_messages[
      !grepl("^boundary \\(singular\\) fit", substantive_messages)
    ]
  }
  conv_messages <- if (length(conv_messages)) paste(conv_messages, collapse = " | ") else NA_character_
  derivs <- fit@optinfo$derivs
  scaled_gradient <- NA_real_
  if (!is.null(derivs$gradient) && !is.null(derivs$Hessian)) {
    scaled_gradient <- tryCatch({
      chol_h <- chol(derivs$Hessian)
      max(abs(backsolve(chol_h, derivs$gradient)))
    }, error = function(e) Inf)
  }
  singular <- lme4::isSingular(fit)
  finite <- all(is.finite(lme4::fixef(fit))) &&
    all(is.finite(unlist(lme4::VarCorr(fit)))) &&
    is.finite(stats::sigma(fit))
  converged <- identical(opt_code, 0L) && length(substantive_messages) == 0 &&
    is.finite(scaled_gradient) && scaled_gradient <= gradient_tol && finite &&
    (allow_singular || !singular)
  list(converged = converged, optimizer_code = opt_code,
       convergence_messages = conv_messages, scaled_gradient = scaled_gradient,
       singular = singular, finite = finite)
}

.m3_zero_matching_variance <- function(fit, tolerance = 1e-7) {
  vc <- as.data.frame(lme4::VarCorr(fit))
  matching_var <- vc$vcov[vc$grp == "matching_id" &
                            vc$var1 == "(Intercept)" & is.na(vc$var2)]
  id_var <- vc$vcov[vc$grp == "id" &
                      vc$var1 == "(Intercept)" & is.na(vc$var2)]
  list(
    permitted = length(matching_var) == 1L && length(id_var) == 1L &&
      is.finite(matching_var) && is.finite(id_var) &&
      matching_var <= tolerance && id_var > tolerance,
    matching_id_variance = if (length(matching_var) == 1L) matching_var else NA_real_
  )
}

.fit_lmer_with_ladder <- function(formula, data, model_label, weights = NULL,
                                  allow_m3_matching_boundary = FALSE) {
  formula_text <- paste(deparse(formula), collapse = "")
  slope_uncorrelated <- as.formula(gsub("\\(1 \\+ Age_Centered \\| id\\)",
                                        "(1 + Age_Centered || id)", formula_text))
  intercept_only <- as.formula(gsub("\\(1 \\+ Age_Centered \\|\\| id\\)|\\(1 \\+ Age_Centered \\| id\\)",
                                    "(1 | id)", formula_text))
  attempts <- list(
    list(
      rung = "correlated random slope",
      formula = formula,
      control = lmerControl(optimizer = "bobyqa", calc.derivs = TRUE,
                            optCtrl = list(maxfun = 2e5))
    ),
    list(
      rung = "uncorrelated random slope",
      formula = slope_uncorrelated,
      control = lmerControl(optimizer = "bobyqa", calc.derivs = TRUE,
                            optCtrl = list(maxfun = 2e5))
    ),
    list(
      rung = "random intercept only",
      formula = intercept_only,
      control = lmerControl(optimizer = "bobyqa", calc.derivs = TRUE,
                            optCtrl = list(maxfun = 2e5))
    )
  )

  last_error <- NULL
  attempt_log <- list()
  for (at in attempts) {
    warnings_seen <- character()
    fit_call <- function() {
      if (is.null(weights)) {
        lme4::lmer(at$formula, data = data, REML = TRUE, control = at$control)
      } else {
        lme4::lmer(at$formula, data = data, REML = TRUE, control = at$control,
                   weights = weights)
      }
    }
    fit <- tryCatch(withCallingHandlers(
      fit_call(),
      warning = function(w) {
        warnings_seen <<- c(warnings_seen, conditionMessage(w))
        invokeRestart("muffleWarning")
      }),
      error = function(e) {
        last_error <<- conditionMessage(e)
        NULL
      }
    )
    if (is.null(fit)) {
      attempt_log[[length(attempt_log) + 1L]] <- data.frame(
        model_label = model_label, rung = at$rung, accepted = FALSE,
        optimizer_code = NA_integer_, convergence_messages = NA_character_,
        scaled_gradient = NA_real_, singular = NA, finite = NA,
        warnings = paste(warnings_seen, collapse = " | "), error = last_error
      )
      next
    }
    boundary_m3 <- if (identical(at$rung, "random intercept only") &&
                       isTRUE(allow_m3_matching_boundary)) {
      .m3_zero_matching_variance(fit)
    } else {
      list(permitted = FALSE, matching_id_variance = NA_real_)
    }
    check <- .assess_lmer_fit(fit, allow_singular = boundary_m3$permitted)
    # Strict acceptance rejects fitting warnings except a boundary warning for
    # M3's intercept-only fallback when only matching_id variance is zero.
    substantive_warnings <- warnings_seen
    if (boundary_m3$permitted && length(substantive_warnings)) {
      substantive_warnings <- substantive_warnings[
        !grepl("^boundary \\(singular\\) fit", substantive_warnings)
      ]
    }
    check$converged <- check$converged && length(substantive_warnings) == 0
    attempt_log[[length(attempt_log) + 1L]] <- data.frame(
      model_label = model_label, rung = at$rung, accepted = check$converged,
      optimizer_code = check$optimizer_code,
      convergence_messages = check$convergence_messages,
      scaled_gradient = check$scaled_gradient, singular = check$singular,
      finite = check$finite, warnings = paste(warnings_seen, collapse = " | "),
      error = NA_character_
    )
    if (check$converged) {
      return(c(list(fit = fit, rung = at$rung, error = NA_character_,
                    attempts = bind_rows(attempt_log),
                    boundary_matching_variance_zero = boundary_m3$permitted,
                    matching_id_variance = boundary_m3$matching_id_variance), check))
    }
    last_error <- paste0(at$rung, " failed strict acceptance checks")
  }

  err <- simpleError(paste0("Could not fit ", model_label, ": ", last_error))
  attr(err, "attempts") <- bind_rows(attempt_log)
  stop(err)
}

.variance_components <- function(model, cohort, model_id) {
  vc <- as.data.frame(lme4::VarCorr(model))
  vc %>% transmute(
    Cohort = cohort, model_id = model_id, grouping_factor = grp,
    term_1 = var1, term_2 = var2, variance = vcov, sd_or_correlation = sdcor
  )
}

.model_diagnostics <- function(model, data, cohort, model_id) {
  rr <- residuals(model)
  ff <- fitted(model)
  residual_frame <- data.frame(Group = as.character(data$Group), residual = rr,
                               fitted = ff, Age_Centered = data$Age_Centered)
  summarize_residuals <- function(x, group_label) {
    qq <- quantile(x$residual, probs = c(0, .01, .05, .25, .5, .75, .95, .99, 1),
                   na.rm = TRUE)
    data.frame(
      Cohort = cohort, model_id = model_id, Group = group_label,
      n = nrow(x), residual_mean = mean(x$residual), residual_sd = sd(x$residual),
      residual_fitted_correlation = cor(x$residual, x$fitted),
      residual_time_correlation = cor(x$residual, x$Age_Centered),
      q0 = qq[[1]], q01 = qq[[2]], q05 = qq[[3]], q25 = qq[[4]],
      q50 = qq[[5]], q75 = qq[[6]], q95 = qq[[7]], q99 = qq[[8]], q100 = qq[[9]]
    )
  }
  residual_summary <- bind_rows(
    summarize_residuals(residual_frame, "All"),
    lapply(split(residual_frame, residual_frame$Group), function(x) {
      summarize_residuals(x, unique(x$Group))
    })
  )
  re_summary <- bind_rows(lapply(names(ranef(model)), function(grp) {
    re <- ranef(model)[[grp]]
    bind_rows(lapply(names(re), function(term) {
      z <- re[[term]]
      data.frame(Cohort = cohort, model_id = model_id,
                 grouping_factor = grp, term = term, n = length(z),
                 mean = mean(z), sd = sd(z), q01 = quantile(z, .01),
                 q50 = median(z), q99 = quantile(z, .99))
    }))
  }))
  list(residual = residual_summary, random_effect = re_summary)
}

.spline_interaction_terms <- function(beta_names, sterms) {
  beta_names[grepl(":", beta_names) & grepl("GroupCancer Case", beta_names) &
               Reduce(`|`, lapply(sterms, grepl, x = beta_names))]
}

run_eventstudy_spline_analysis <- function(matched_path,
                                           results_dir,
                                           visuals_dir,
                                           out_prefix,
                                           analysis_title,
                                           builder_script,
                                           window_yrs   = 20,
                                           spline_df    = 4,
                                           min_case_bin = 50,
                                           min_ctrl_bin = 250) {

  needed_cols <- c("Cohort", "Group", "Age_Centered", "index_age_z",
                   "base_race", "base_marital", "base_living", "base_pckgr",
                   "id", "match_set", "role", "cycle", "fi_score_nocancer")

  if (!file.exists(matched_path)) {
    stop("Matched dataset not found at ", matched_path, ". Run ", builder_script, " first.")
  }

  matching_provenance <- validate_matching_provenance(matched_path)
  matched_long <- readRDS(matched_path)
  if (!("control_cancer_free_through_endpoint" %in% names(matched_long))) {
    stop(
      "Matched dataset is missing the 9.xx cancer-free-through-endpoint flag.",
      call. = FALSE
    )
  }
  bad_endpoint_controls <- matched_long %>%
    filter(
      role == "Control",
      !control_cancer_free_through_endpoint
    )
  if (nrow(bad_endpoint_controls) > 0L) {
    stop(
      "The 9.xx matched dataset contains controls with cancer on or before ",
      "the full HPFS endpoint.",
      call. = FALSE
    )
  }
  missing_cols <- setdiff(needed_cols, names(matched_long))
  if (length(missing_cols) > 0) {
    stop("Matched dataset is missing required columns: ", paste(missing_cols, collapse = ", "))
  }

  if (!("matching_id" %in% names(matched_long))) {
    matched_long <- matched_long %>%
      mutate(matching_id = paste(Cohort, match_set, sep = "__"))
  }
  if (!("trajectory_id" %in% names(matched_long))) {
    matched_long <- matched_long %>%
      mutate(trajectory_id = paste(Cohort, match_set, id, role, sep = "__"))
  }
  if (!("post_own_cancer" %in% names(matched_long))) {
    stop("Matched dataset is missing post_own_cancer. Rebuild it with 2.0_riskset_matching_functions.R before fitting GLME models.")
  }

  n_post_own_cancer_rows <- sum(matched_long$post_own_cancer %in% TRUE, na.rm = TRUE)
  censoring_log <- matched_long %>%
    group_by(Cohort, Group, role) %>%
    summarize(
      n_rows_before_own_cancer_censoring = n(),
      n_rows_removed_post_own_cancer = sum(post_own_cancer),
      n_rows_after_own_cancer_censoring = sum(!post_own_cancer),
      n_assignments_with_rows_removed = n_distinct(trajectory_id[post_own_cancer]),
      .groups = "drop"
    )

  matched_long <- matched_long %>%
    mutate(
      Cohort    = droplevels(factor(Cohort)),
      Group     = factor(Group, levels = c("Control", "Cancer Case")),
      id        = factor(id),
      match_set = factor(match_set),
      matching_id = factor(matching_id),
      trajectory_id = factor(trajectory_id),
      base_race = factor(base_race),
      base_marital = factor(base_marital),
      base_living = factor(base_living),
      base_pckgr = factor(base_pckgr)
    ) %>%
    # Future cases remain eligible controls at an earlier index, but primary
    # follow-up ends at that control's own subsequent cancer diagnosis.
    filter(!post_own_cancer, !is.na(fi_score_nocancer), !is.na(Age_Centered)) %>%
    add_relative_time_bin()

  if (anyDuplicated(paste(matched_long$trajectory_id, matched_long$cycle, sep = "__"))) {
    stop("Duplicated trajectory_id x cycle rows remain after primary filtering.")
  }

  message("Primary own-cancer censoring removed ", n_post_own_cancer_rows,
          " control rows at/after a later own cancer diagnosis.")

  cohorts <- levels(matched_long$Cohort)
  group_cols <- c("Control" = "#3182bd", "Cancer Case" = "#de2d26")

  es_coef_all   <- list()
  es_pred_all   <- list()
  es_tests_all  <- list()
  support_all   <- list()
  filter_all    <- list()
  metadata_all  <- list()
  sp_pred_all   <- list()
  sp_diff_all   <- list()
  sp_deriv_all  <- list()
  sp_coef_all   <- list()
  sp_theta_all  <- list()
  sp_status_all <- list()
  convergence_all <- list()
  variance_all <- list()
  residual_diag_all <- list()
  random_effect_diag_all <- list()
  bounded_diag_all <- list()
  omnibus_all <- list()
  influence_all <- list()
  scaling_all <- list()
  es_models     <- list()
  sp_models     <- list()

  for (ch in cohorts) {

    d_base <- matched_long %>%
      filter(Cohort == ch) %>%
      droplevels()

    filter_all[[ch]] <- bind_rows(lapply(names(.spline_model_specs), function(model_id) {
      spec <- .spline_model_specs[[model_id]]
      d_model_check <- d_base %>% filter(if_all(all_of(spec$covars), ~ !is.na(.x)))
      before <- d_base %>% distinct(Group, trajectory_id) %>%
        count(Group, name = "n_before_complete_case")
      after <- d_model_check %>% distinct(Group, trajectory_id) %>%
        count(Group, name = "n_after_complete_case")
      before %>%
        left_join(after, by = "Group") %>%
        mutate(
          Cohort = ch, model_id = model_id,
          n_after_complete_case = if_else(is.na(n_after_complete_case), 0L,
                                          n_after_complete_case),
          n_dropped_complete_case = n_before_complete_case - n_after_complete_case,
          pct_dropped_complete_case = 100 * n_dropped_complete_case / n_before_complete_case
        )
    }))
    if (any(filter_all[[ch]]$pct_dropped_complete_case > 5, na.rm = TRUE)) {
      warning("Complete-case filtering removes more than 5% of rows in at least one arm/model for ",
              ch, ". See the model filter log.", call. = FALSE)
    }

    d_es <- d_base %>%
      filter(if_all(all_of(.primary_covars), ~ !is.na(.x))) %>%
      droplevels()

    # ---- bin support; drop bins lacking both-arm support, keep reference ----
    support <- d_es %>%
      group_by(rel_time_bin, .drop = FALSE) %>%
      summarize(
        n_case = n_distinct(id[Group == "Cancer Case"]),
        n_ctrl = n_distinct(id[Group == "Control"]),
        .groups = "drop"
      ) %>%
      mutate(
        support_ok = (n_case >= min_case_bin & n_ctrl >= min_ctrl_bin)
      )

    support_all[[ch]] <- support %>% mutate(Cohort = ch, analysis = "event_study_M1")

    cat("\n======== Event-study cohort:", ch, "========\n")
    cat("Bin support (distinct ids); bins with no case or no control are dropped:\n")
    print(as.data.frame(support), row.names = FALSE)

    keep_bins <- as.character(support$rel_time_bin[support$support_ok])
    if (!(.es_ref_label %in% keep_bins)) {
      stop("Reference bin '", .es_ref_label, "' has no both-arm support in cohort ", ch)
    }

    d_es <- d_es %>%
      filter(as.character(rel_time_bin) %in% keep_bins) %>%
      mutate(rel_time_bin = relevel(droplevels(factor(rel_time_bin)),
                                    ref = .es_ref_label))

    # ---------------------------- 1) event-study GLME ---------------------------
    es_fixed_rhs <- .fixed_rhs(covars = .primary_covars,
                               time_term = "rel_time_bin")

    m_es_info <- .fit_lmer_with_ladder(
      update(es_fixed_rhs, fi_score_nocancer ~ . + (1 | id)), d_es,
      paste0("event study ", ch)
    )
    m_es <- m_es_info$fit
    convergence_all[[paste(ch, "event_study", sep = "__")]] <-
      m_es_info$attempts %>% mutate(Cohort = ch, model_id = "event_study", .before = 1)
    es_models[[ch]] <- m_es

    beta <- fixef(m_es)
    Vcr  <- get_primary_vcov(m_es, d_es$id, cluster_name = "id")
    Ves  <- Vcr$V
    se   <- sqrt(diag(Ves))

    coef_tab <- coef_table_with_vcov(m_es, Vcr) %>%
      mutate(Cohort = ch, vcov_type = Vcr$type, .before = 1)
    es_coef_all[[ch]] <- coef_tab

    # event-study interaction terms -> per-bin gap relative to reference bin
    es_it     <- .es_interaction_terms(names(beta))
    int_terms <- es_it$term
    mids      <- .es_bin_midpoints[es_it$bin]

    # joint Wald tests (global / pre-index / post-index interaction terms)
    pre_terms  <- int_terms[!is.na(mids) & mids < 0]
    post_terms <- int_terms[!is.na(mids) & mids > 0]
    es_tests_all[[ch]] <- bind_rows(
      joint_wald(m_es, Vcr, int_terms,  "Global: any differential trajectory"),
      joint_wald(m_es, Vcr, pre_terms,  "Pre-index: parallel-trends test"),
      joint_wald(m_es, Vcr, post_terms, "Post-index: differential post-diagnosis")
    ) %>% mutate(Cohort = ch, vcov_type = Vcr$type, .before = 1)

    # ---- step predicted means by bin x group (model-based mean + CR2 CI) ----
    grid_es <- .make_ref_grid(
      d_es,
      rel_time_bin = levels(d_es$rel_time_bin),
      Group = c("Control", "Cancer Case")
    ) %>%
      mutate(
        rel_time_bin = factor(rel_time_bin, levels = levels(d_es$rel_time_bin)),
        Group = factor(Group, levels = c("Control", "Cancer Case")),
        mid = .es_bin_midpoints[as.character(rel_time_bin)]
      )
    Xes <- model.matrix(es_fixed_rhs, data = grid_es)[, names(beta), drop = FALSE]
    pe  <- as.vector(Xes %*% beta)
    sde <- sqrt(rowSums((Xes %*% Ves) * Xes))
    grid_es$pred <- pe; grid_es$lwr <- pe - 1.96 * sde; grid_es$upr <- pe + 1.96 * sde
    grid_es$Cohort <- ch
    grid_es$vcov_type <- Vcr$type
    es_pred_all[[ch]] <- grid_es

    # ---------------------------- 2) natural-spline GLME/LME model set ---------
    # Build one canonical spline basis from the primary-model fitting sample;
    # all M0--M3 variants use these same knots and boundaries.
    d_spline_basis <- d_base %>%
      filter(if_all(all_of(.primary_covars), ~ !is.na(.x)))
    bk <- range(d_spline_basis$Age_Centered, na.rm = TRUE)
    ik <- as.numeric(quantile(
      d_spline_basis$Age_Centered,
      probs = seq(0, 1, length.out = spline_df + 1)[-c(1, spline_df + 1)],
      na.rm = TRUE
    ))
    Bobj <- ns(d_spline_basis$Age_Centered, knots = ik, Boundary.knots = bk)
    sterms <- paste0("S", seq_len(ncol(Bobj)))
    metadata_all[[ch]] <- list(
      schema_version = 1L,
      generated_at = format(Sys.time(), tz = "UTC", usetz = TRUE),
      cohort = ch,
      outcome = "fi_score_nocancer",
      spline_df = spline_df,
      knots = attr(Bobj, "knots"),
      boundary_knots = attr(Bobj, "Boundary.knots"),
      fitting_time_range = range(d_spline_basis$Age_Centered, na.rm = TRUE),
      n_obs = nrow(d_spline_basis),
      n_id = n_distinct(d_spline_basis$id),
      n_trajectory_id = n_distinct(d_spline_basis$trajectory_id),
      n_matching_id = n_distinct(d_spline_basis$matching_id),
      prediction_window_requested = c(-window_yrs, window_yrs),
      theta_windows = list(pre = c(-8, 0), post = c(0, 8)),
      primary_covariates = .primary_covars,
      own_cancer_censored_rows = n_post_own_cancer_rows,
      matching_input_md5 = matching_provenance$input_md5,
      control_cancer_free_rule =
        matching_provenance$run_metadata$control_cancer_free_rule,
      control_cancer_free_cutoff =
        matching_provenance$run_metadata$control_cancer_free_cutoff,
      control_cancer_free_cutoff_units =
        matching_provenance$run_metadata$control_cancer_free_cutoff_units
    )
    d_sp_all <- bind_cols(
      d_base,
      setNames(as.data.frame(predict(Bobj, d_base$Age_Centered)), sterms)
    )

    sp_models[[ch]] <- list()
    sp_pred_all[[ch]] <- list()
    sp_diff_all[[ch]] <- list()
    sp_deriv_all[[ch]] <- list()
    sp_coef_all[[ch]] <- list()
    sp_theta_all[[ch]] <- list()
    sp_status_all[[ch]] <- list()
    metadata_all[[ch]]$model_scaling <- list()

    for (model_id in names(.spline_model_specs)) {
      spec <- .spline_model_specs[[model_id]]
      missing_model_cols <- setdiff(c(spec$covars, sterms), names(d_sp_all))
      if (length(missing_model_cols) > 0) {
        msg <- paste("Skipped", spec$label, "for", ch,
                     "- missing columns:",
                     paste(missing_model_cols, collapse = ", "),
                     ". Rerun upstream cleaning/matching if baseline nutrition variables are expected.")
        message(msg)
        sp_status_all[[ch]][[model_id]] <- data.frame(
          Cohort = ch, model_id = model_id, model_label = spec$label,
          model_role = spec$role, status = "skipped_missing_columns",
          n_obs = NA_integer_, n_id = NA_integer_, n_matching_id = NA_integer_,
          fitting_min_time = NA_real_, fitting_max_time = NA_real_,
          rung = NA_character_, singular = NA, vcov_type = NA_character_,
          message = msg
        )
        next
      }

      d_model <- d_sp_all %>%
        filter(if_all(all_of(spec$covars), ~ !is.na(.x))) %>%
        droplevels()

      # This is a purely numerical reparameterization: centering/scaling the
      # spline basis retains the same fixed-effect column space, while M2's
      # continuous dietary covariates need commensurate scales with the spline
      # and factor columns.  Store every parameter for exact grid reconstruction.
      scaling_columns <- sterms
      if (identical(model_id, "M2_full")) {
        scaling_columns <- c(scaling_columns,
                             c("base_calor", "base_sat", "base_diet_chol", "base_alco"))
      }
      scaling <- .scale_model_numeric_columns(d_model, scaling_columns)
      d_model <- scaling$data
      metadata_all[[ch]]$model_scaling[[model_id]] <- scaling$parameters
      scaling_all[[paste(ch, model_id, sep = "__")]] <-
        scaling$parameters %>%
        mutate(Cohort = ch, model_id = model_id, model_label = spec$label,
               .before = 1)

      if (length(unique(d_model$Group)) < 2 || nrow(d_model) == 0) {
        msg <- paste("Skipped", spec$label, "for", ch,
                     "- insufficient two-arm support after model-specific complete-case filtering.")
        message(msg)
        sp_status_all[[ch]][[model_id]] <- data.frame(
          Cohort = ch, model_id = model_id, model_label = spec$label,
          model_role = spec$role, status = "skipped_insufficient_support",
          n_obs = nrow(d_model), n_id = n_distinct(d_model$id),
          n_matching_id = n_distinct(d_model$matching_id),
          fitting_min_time = suppressWarnings(min(d_model$Age_Centered, na.rm = TRUE)),
          fitting_max_time = suppressWarnings(max(d_model$Age_Centered, na.rm = TRUE)),
          rung = NA_character_, singular = NA, vcov_type = NA_character_,
          message = msg
        )
        next
      }

      model_support <- d_model %>%
        group_by(rel_time_bin, .drop = FALSE) %>%
        summarize(
          n_case = n_distinct(id[Group == "Cancer Case"]),
          n_ctrl = n_distinct(id[Group == "Control"]),
          .groups = "drop"
        ) %>%
        mutate(
          support_ok = n_case >= min_case_bin & n_ctrl >= min_ctrl_bin,
          Cohort = ch, analysis = paste0("spline_", model_id)
        )
      support_all[[paste(ch, model_id, sep = "__")]] <- model_support
      prediction_window <- continuous_support_window(model_support, window_yrs)
      if (anyNA(prediction_window) || prediction_window[[1]] >= prediction_window[[2]]) {
        msg <- paste("Skipped", spec$label, "for", ch,
                     "- no continuous two-arm support meeting the configured thresholds.")
        message(msg)
        sp_status_all[[ch]][[model_id]] <- data.frame(
          Cohort = ch, model_id = model_id, model_label = spec$label,
          model_role = spec$role, status = "skipped_insufficient_supported_window",
          n_obs = nrow(d_model), n_id = n_distinct(d_model$id),
          n_matching_id = n_distinct(d_model$matching_id),
          fitting_min_time = min(d_model$Age_Centered, na.rm = TRUE),
          fitting_max_time = max(d_model$Age_Centered, na.rm = TRUE),
          prediction_min_time = NA_real_, prediction_max_time = NA_real_,
          rung = NA_character_, singular = NA, vcov_type = NA_character_,
          message = msg
        )
        next
      }

      sp_fixed_rhs <- .fixed_rhs(spline_terms = sterms, covars = spec$covars)
      random_rhs <- if (model_id == "M3_primary_matching") {
        "(1 + Age_Centered | id) + (1 | matching_id)"
      } else {
        "(1 + Age_Centered | id)"
      }
      model_formula <- as.formula(paste(
        "fi_score_nocancer",
        paste(deparse(sp_fixed_rhs), collapse = ""),
        "+",
        random_rhs
      ))

      fit_info <- tryCatch(
        .fit_lmer_with_ladder(
          model_formula, d_model, spec$label,
          allow_m3_matching_boundary = identical(model_id, "M3_primary_matching")
        ),
        error = function(e) e
      )
      if (inherits(fit_info, "error")) {
        convergence_all[[paste(ch, model_id, sep = "__")]] <-
          attr(fit_info, "attempts") %>%
          mutate(Cohort = ch, model_id = model_id, .before = 1)
        msg <- conditionMessage(fit_info)
        sp_status_all[[ch]][[model_id]] <- data.frame(
          Cohort = ch, model_id = model_id, model_label = spec$label,
          model_role = spec$role, status = "failed_strict_convergence",
          n_obs = nrow(d_model), n_id = n_distinct(d_model$id),
          n_matching_id = n_distinct(d_model$matching_id),
          fitting_min_time = min(d_model$Age_Centered, na.rm = TRUE),
          fitting_max_time = max(d_model$Age_Centered, na.rm = TRUE),
          prediction_min_time = prediction_window[[1]],
          prediction_max_time = prediction_window[[2]],
          rung = NA_character_, singular = NA, convergence = FALSE,
          optimizer_code = NA_integer_, scaled_gradient = NA_real_,
          convergence_messages = NA_character_, vcov_type = NA_character_,
          message = msg
        )
        next
      }
      m_sp <- fit_info$fit
      convergence_all[[paste(ch, model_id, sep = "__")]] <-
        fit_info$attempts %>% mutate(Cohort = ch, model_id = model_id, .before = 1)
      sp_models[[ch]][[model_id]] <- m_sp

      beta_sp <- fixef(m_sp)
      Vobj <- get_primary_vcov(m_sp, d_model$id, cluster_name = "id")
      Vsp <- Vobj$V
      se_sp <- sqrt(diag(Vsp))

      variance_all[[paste(ch, model_id, sep = "__")]] <-
        .variance_components(m_sp, ch, model_id)
      dg <- .model_diagnostics(m_sp, d_model, ch, model_id)
      residual_diag_all[[paste(ch, model_id, sep = "__")]] <- dg$residual
      random_effect_diag_all[[paste(ch, model_id, sep = "__")]] <- dg$random_effect

      sp_coef_all[[ch]][[model_id]] <- coef_table_with_vcov(m_sp, Vobj) %>%
        mutate(Cohort = ch, model_id = model_id, model_label = spec$label,
               model_role = spec$role, vcov_type = Vobj$type, .before = 1)

      make_sp_grid <- function(age_values, group_value) {
        g <- .make_ref_grid(
          d_model,
          covars = spec$covars,
          Age_Centered = age_values,
          Group = group_value
        ) %>%
          mutate(Group = factor(Group, levels = c("Control", "Cancer Case")))
        Bp <- predict(Bobj, g$Age_Centered)
        bind_cols(g, setNames(as.data.frame(Bp), sterms)) %>%
          .apply_model_scaling(scaling$parameters)
      }

      pred_age <- seq(prediction_window[[1]], prediction_window[[2]], by = 0.25)
      grid_sp <- .make_ref_grid(
        d_model,
        covars = spec$covars,
        Age_Centered = pred_age,
        Group = c("Control", "Cancer Case")
      ) %>%
        mutate(Group = factor(Group, levels = c("Control", "Cancer Case")))
      Bp <- predict(Bobj, grid_sp$Age_Centered)
      grid_sp <- bind_cols(grid_sp, setNames(as.data.frame(Bp), sterms)) %>%
        .apply_model_scaling(scaling$parameters)

      Xsp <- model.matrix(sp_fixed_rhs, data = grid_sp)[, names(beta_sp), drop = FALSE]
      ps  <- as.vector(Xsp %*% beta_sp)
      sds <- sqrt(rowSums((Xsp %*% Vsp) * Xsp))
      grid_sp$pred <- ps
      grid_sp$se <- sds
      grid_sp$lwr <- ps - 1.96 * sds
      grid_sp$upr <- ps + 1.96 * sds
      grid_sp$Cohort <- ch
      grid_sp$model_id <- model_id
      grid_sp$model_label <- spec$label
      grid_sp$model_role <- spec$role
      grid_sp$vcov_type <- Vobj$type
      bounded_diag_all[[paste(ch, model_id, sep = "__")]] <- data.frame(
        Cohort = ch, model_id = model_id, n_predictions = nrow(grid_sp),
        n_point_outside_0_1 = sum(grid_sp$pred < 0 | grid_sp$pred > 1),
        n_ci_outside_0_1 = sum(grid_sp$lwr < 0 | grid_sp$upr > 1),
        min_prediction = min(grid_sp$pred), max_prediction = max(grid_sp$pred),
        min_ci = min(grid_sp$lwr), max_ci = max(grid_sp$upr)
      )
      sp_pred_all[[ch]][[model_id]] <- grid_sp[, c(
        "Cohort", "model_id", "model_label", "model_role", "Group",
        "Age_Centered", "pred", "se", "lwr", "upr", "vcov_type"
      )]

      grid_case <- make_sp_grid(pred_age, "Cancer Case")
      grid_ctrl <- make_sp_grid(pred_age, "Control")
      X_case <- model.matrix(sp_fixed_rhs, data = grid_case)[, names(beta_sp), drop = FALSE]
      X_ctrl <- model.matrix(sp_fixed_rhs, data = grid_ctrl)[, names(beta_sp), drop = FALSE]
      X_diff <- X_case - X_ctrl
      diff_est <- as.vector(X_diff %*% beta_sp)
      diff_se <- sqrt(rowSums((X_diff %*% Vsp) * X_diff))
      sp_diff_all[[ch]][[model_id]] <- data.frame(
        Cohort = ch, model_id = model_id, model_label = spec$label,
        model_role = spec$role, Age_Centered = pred_age,
        diff = diff_est, se = diff_se,
        lwr = diff_est - 1.96 * diff_se,
        upr = diff_est + 1.96 * diff_se,
        vcov_type = Vobj$type
      )

      deriv_row <- function(t, h = 1e-4) {
        c_plus <- make_sp_grid(t + h, "Cancer Case")
        c_minus <- make_sp_grid(t - h, "Cancer Case")
        r_plus <- make_sp_grid(t + h, "Control")
        r_minus <- make_sp_grid(t - h, "Control")
        (model.matrix(sp_fixed_rhs, data = c_plus)[, names(beta_sp), drop = FALSE] -
           model.matrix(sp_fixed_rhs, data = c_minus)[, names(beta_sp), drop = FALSE] -
           model.matrix(sp_fixed_rhs, data = r_plus)[, names(beta_sp), drop = FALSE] +
           model.matrix(sp_fixed_rhs, data = r_minus)[, names(beta_sp), drop = FALSE]) /
          (2 * h)
      }
      deriv_X <- do.call(rbind, lapply(pred_age, deriv_row))
      deriv_est <- as.vector(deriv_X %*% beta_sp)
      deriv_se <- sqrt(rowSums((deriv_X %*% Vsp) * deriv_X))
      sp_deriv_all[[ch]][[model_id]] <- data.frame(
        Cohort = ch, model_id = model_id, model_label = spec$label,
        model_role = spec$role, Age_Centered = pred_age,
        derivative = deriv_est, se = deriv_se,
        lwr = deriv_est - 1.96 * deriv_se,
        upr = deriv_est + 1.96 * deriv_se,
        vcov_type = Vobj$type,
        infer_method = paste(Vobj$type, "normal approximation")
      )
      theta_supported <- prediction_window[[1]] <= -8 && prediction_window[[2]] >= 8
      theta_grid_post <- seq(0.025, 7.975, by = 0.05)
      theta_grid_pre <- seq(-7.975, -0.025, by = 0.05)
      c_post <- colMeans(do.call(rbind, lapply(theta_grid_post, deriv_row)))
      c_pre <- colMeans(do.call(rbind, lapply(theta_grid_pre, deriv_row)))
      c_theta <- c_post - c_pre
      theta <- if (theta_supported) as.numeric(c_theta %*% beta_sp) else NA_real_
      theta_se <- if (theta_supported) sqrt(as.numeric(t(c_theta) %*% Vsp %*% c_theta)) else NA_real_
      theta_test <- if (theta_supported) {
        wald_with_vcov(m_sp, Vobj, matrix(c_theta, nrow = 1), "theta")
      } else {
        data.frame(Test = "theta", Fstat = NA_real_, df_num = 1,
                   df_denom = NA_real_, p_value = NA_real_, infer_method = Vobj$type)
      }
      theta_df <- theta_test$df_denom[[1]]
      theta_crit <- if (is.finite(theta_df)) qt(0.975, df = theta_df) else qnorm(0.975)
      pre_theta <- if (theta_supported) as.numeric(c_pre %*% beta_sp) else NA_real_
      pre_theta_se <- if (theta_supported) sqrt(as.numeric(t(c_pre) %*% Vsp %*% c_pre)) else NA_real_
      endpoint_diff <- function(t) {
        xx <- model.matrix(sp_fixed_rhs, data = make_sp_grid(t, "Cancer Case"))[, names(beta_sp), drop = FALSE] -
          model.matrix(sp_fixed_rhs, data = make_sp_grid(t, "Control"))[, names(beta_sp), drop = FALSE]
        as.numeric(xx %*% beta_sp)
      }
      theta_closed_form <- if (theta_supported) {
        (endpoint_diff(8) - endpoint_diff(0)) / 8 -
          (endpoint_diff(0) - endpoint_diff(-8)) / 8
      } else NA_real_
      theta_difference <- theta - theta_closed_form
      if (theta_supported && (!is.finite(theta_difference) || abs(theta_difference) > 1e-6)) {
        stop("Numerical and closed-form theta differ by more than 1e-6 for ",
             ch, " / ", model_id, ": ", format(theta_difference, digits = 12), call. = FALSE)
      }
      pre_constraint <- matrix(c_pre, nrow = 1)
      pre_test <- if (theta_supported) {
        wald_with_vcov(m_sp, Vobj, pre_constraint, "pre-index average differential slope")
      } else data.frame(p_value = NA_real_, df_denom = NA_real_)
      pre_df <- pre_test$df_denom[[1]]
      pre_crit <- if (is.finite(pre_df)) qt(0.975, df = pre_df) else qnorm(0.975)
      interaction_terms <- .spline_interaction_terms(names(beta_sp), sterms)
      omnibus_all[[paste(ch, model_id, sep = "__")]] <-
        joint_wald(m_sp, Vobj, interaction_terms,
                   "trajectory-shape difference (secondary)") %>%
        mutate(Cohort = ch, model_id = model_id, .before = 1)
      sp_theta_all[[ch]][[model_id]] <- data.frame(
        Cohort = ch, model_id = model_id, model_label = spec$label,
        model_role = spec$role, theta = theta, se = theta_se,
        df = theta_df, p_value = theta_test$p_value[[1]],
        lwr = theta - theta_crit * theta_se,
        upr = theta + theta_crit * theta_se,
        theta_closed_form = theta_closed_form,
        theta_closed_form_difference = theta_difference,
        pre_index_slope = pre_theta, pre_index_slope_se = pre_theta_se,
        pre_index_slope_lwr = pre_theta - pre_crit * pre_theta_se,
        pre_index_slope_upr = pre_theta + pre_crit * pre_theta_se,
        pre_index_slope_df = pre_df,
        pre_index_slope_p = pre_test$p_value[[1]],
        pre_index_slope_infer_method = if ("infer_method" %in% names(pre_test)) pre_test$infer_method[[1]] else Vobj$type,
        pre_window = "[-8, 0)", post_window = "(0, +8]",
        theta_supported = theta_supported,
        prediction_min_time = prediction_window[[1]],
        prediction_max_time = prediction_window[[2]],
        vcov_type = Vobj$type
      )

      # Deterministic grouped jackknife: sort matched sets, assign ten nearly
      # equal groups, and refit M1 after dropping each group in turn.
      if (identical(model_id, "M1_primary") && theta_supported) {
        set_ids <- sort(unique(as.character(d_model$matching_id)))
        decile_map <- setNames(pmin(10L, ceiling(seq_along(set_ids) * 10 / length(set_ids))),
                               set_ids)
        influence_all[[ch]] <- bind_rows(lapply(seq_len(10), function(decile) {
          d_jk <- d_model[decile_map[as.character(d_model$matching_id)] != decile, , drop = FALSE]
          jk <- tryCatch(.fit_lmer_with_ladder(model_formula, d_jk,
                                               paste0(spec$label, " influence decile ", decile)),
                         error = function(e) e)
          if (inherits(jk, "error")) {
            return(data.frame(Cohort = ch, model_id = model_id,
                              dropped_matching_id_decile = decile,
                              n_obs = nrow(d_jk), theta = NA_real_,
                              theta_change = NA_real_, pct_theta_change = NA_real_,
                              rung = NA_character_, status = conditionMessage(jk)))
          }
          theta_jk <- as.numeric(c_theta %*% fixef(jk$fit))
          data.frame(Cohort = ch, model_id = model_id,
                     dropped_matching_id_decile = decile,
                     n_obs = nrow(d_jk), theta = theta_jk,
                     theta_change = theta_jk - theta,
                     pct_theta_change = if (theta == 0) NA_real_ else 100 * (theta_jk - theta) / abs(theta),
                     rung = jk$rung, status = "fit")
        }))
      }

      sp_status_all[[ch]][[model_id]] <- data.frame(
        Cohort = ch, model_id = model_id, model_label = spec$label,
        model_role = spec$role,
        status = if (isTRUE(fit_info$boundary_matching_variance_zero)) {
          "fit_boundary_matching_variance_zero"
        } else "fit",
        n_obs = nrow(d_model), n_id = n_distinct(d_model$id),
        n_matching_id = n_distinct(d_model$matching_id),
          fitting_min_time = min(d_model$Age_Centered, na.rm = TRUE),
          fitting_max_time = max(d_model$Age_Centered, na.rm = TRUE),
          prediction_min_time = prediction_window[[1]],
          prediction_max_time = prediction_window[[2]],
        rung = fit_info$rung, singular = fit_info$singular,
        convergence = fit_info$converged,
        optimizer_code = fit_info$optimizer_code,
        scaled_gradient = fit_info$scaled_gradient,
        convergence_messages = fit_info$convergence_messages,
        vcov_type = Vobj$type,
        matching_id_variance = fit_info$matching_id_variance,
        message = if (isTRUE(fit_info$boundary_matching_variance_zero)) {
          "matching_id intercept variance was on the permitted zero boundary"
        } else NA_character_
      )
    }
  }

  es_coef   <- bind_rows(es_coef_all)
  es_pred   <- bind_rows(es_pred_all)   %>% mutate(Cohort = factor(Cohort, levels = cohorts))
  es_tests  <- bind_rows(es_tests_all)
  support   <- bind_rows(support_all)
  filter_log <- bind_rows(filter_all)
  es_points <- bind_rows(lapply(cohorts, function(ch) {
    coef_tab <- es_coef_all[[ch]]
    beta <- setNames(coef_tab$Estimate, coef_tab$Term)
    se   <- setNames(coef_tab$SE, coef_tab$Term)
    es_it <- .es_interaction_terms(names(beta))
    bind_rows(
      data.frame(Cohort = ch, rel_time_bin = es_it$bin,
                 estimate = as.numeric(beta[es_it$term]), se = se[es_it$term]),
      data.frame(Cohort = ch, rel_time_bin = .es_ref_label, estimate = 0, se = 0)
    )
  })) %>%
    mutate(mid = .es_bin_midpoints[rel_time_bin],
           CI_low = estimate - 1.96 * se, CI_high = estimate + 1.96 * se,
           Cohort = factor(Cohort, levels = cohorts)) %>%
    arrange(Cohort, mid)
  sp_pred <- bind_rows(unlist(sp_pred_all, recursive = FALSE)) %>%
    mutate(Cohort = factor(Cohort, levels = cohorts))
  sp_diff <- bind_rows(unlist(sp_diff_all, recursive = FALSE)) %>%
    mutate(Cohort = factor(Cohort, levels = cohorts))
  sp_deriv <- bind_rows(unlist(sp_deriv_all, recursive = FALSE)) %>%
    mutate(Cohort = factor(Cohort, levels = cohorts))
  sp_coef <- bind_rows(unlist(sp_coef_all, recursive = FALSE)) %>%
    mutate(Cohort = factor(Cohort, levels = cohorts))
  sp_theta <- bind_rows(unlist(sp_theta_all, recursive = FALSE)) %>%
    mutate(Cohort = factor(Cohort, levels = cohorts))
  sp_status <- bind_rows(unlist(sp_status_all, recursive = FALSE)) %>%
    mutate(Cohort = factor(Cohort, levels = cohorts))
  convergence_log <- bind_rows(convergence_all)
  variance_components <- bind_rows(variance_all)
  residual_diagnostics <- bind_rows(residual_diag_all)
  random_effect_diagnostics <- bind_rows(random_effect_diag_all)
  bounded_diagnostics <- bind_rows(bounded_diag_all)
  spline_omnibus <- bind_rows(omnibus_all)
  influence_diagnostics <- bind_rows(influence_all)
  spline_scaling <- bind_rows(scaling_all)
  sp_pred_primary <- sp_pred %>% filter(model_id == "M1_primary")

  cat("\n---- Joint Wald tests (CR2) ----\n"); print(es_tests, row.names = FALSE)

  # --------------------------------- figures ----------------------------------
  p_event <- ggplot(es_points, aes(x = mid, y = estimate)) +
    geom_hline(yintercept = 0, color = "grey40") +
    geom_vline(xintercept = 0, linetype = "dashed", color = "black", alpha = 0.6) +
    geom_errorbar(aes(ymin = CI_low, ymax = CI_high), width = 0.6, color = "#de2d26") +
    geom_point(size = 2, color = "#de2d26") +
    geom_line(color = "#de2d26", alpha = 0.5) +
    facet_wrap(~ Cohort) +
    theme_minimal(base_size = 14) +
    theme(panel.grid.minor = element_blank()) +
    labs(title = analysis_title,
         subtitle = "Event-study: case-vs-control FI gap per 2-year bin (ref = -2 to 0); CR2 95% CIs",
         x = "Years relative to index (bin midpoint)",
         y = "Cancer - Control difference in FI vs reference bin") +
    scale_x_continuous(breaks = seq(-window_yrs, window_yrs, by = 4))

  p_step <- ggplot(es_pred, aes(x = mid, y = pred, color = Group, fill = Group)) +
    geom_vline(xintercept = 0, linetype = "dashed", color = "black", alpha = 0.6) +
    geom_errorbar(aes(ymin = lwr, ymax = upr), width = 0.5,
                  position = position_dodge(width = 0.6)) +
    geom_point(position = position_dodge(width = 0.6), size = 2) +
    geom_step(direction = "mid", alpha = 0.5) +
    facet_wrap(~ Cohort) +
    scale_color_manual(values = group_cols) +
    scale_fill_manual(values = group_cols) +
    theme_minimal(base_size = 14) +
    theme(legend.position = "bottom", panel.grid.minor = element_blank()) +
    labs(title = analysis_title,
         subtitle = "Event-study predicted mean FI by bin (CR2 95% CIs)",
         x = "Years relative to index (bin midpoint)",
         y = "Predicted frailty index (no-cancer FI)", color = NULL, fill = NULL) +
    scale_x_continuous(breaks = seq(-window_yrs, window_yrs, by = 4))

  p_spline <- ggplot(sp_pred_primary, aes(x = Age_Centered, y = pred, color = Group, fill = Group)) +
    geom_ribbon(aes(ymin = lwr, ymax = upr), alpha = 0.18, color = NA) +
    geom_line(linewidth = 1.2) +
    geom_vline(xintercept = 0, linetype = "dashed", color = "black", alpha = 0.6) +
    facet_wrap(~ Cohort) +
    scale_color_manual(values = group_cols) +
    scale_fill_manual(values = group_cols) +
    theme_minimal(base_size = 14) +
    theme(legend.position = "bottom", panel.grid.minor = element_blank()) +
    labs(title = analysis_title,
         subtitle = paste0("Natural-spline smooth companion (df = ", spline_df,
                           "); M1 primary Gaussian LME; centered on own attained age at index"),
         x = "Years relative to index",
         y = "Predicted frailty index (no-cancer FI)", color = NULL, fill = NULL) +
    scale_x_continuous(breaks = seq(-window_yrs, window_yrs, by = 4))

  # --------------------------------- outputs ----------------------------------
  if (!dir.exists(results_dir)) dir.create(results_dir, recursive = TRUE)
  if (!dir.exists(visuals_dir)) dir.create(visuals_dir, recursive = TRUE)

  figure_pdf <- file.path(visuals_dir, paste0(out_prefix, "_GLME_figures.pdf"))
  grDevices::pdf(figure_pdf, width = 8, height = 5.5, onefile = TRUE)
  on.exit(grDevices::dev.off(), add = TRUE)
  print(p_event)
  print(p_step)
  print(p_spline)

  write.csv(es_coef, file.path(results_dir, paste0(out_prefix, "_eventstudy_fixed_effects_CI.csv")),
            row.names = FALSE)
  write.csv(es_points[, c("Cohort", "rel_time_bin", "mid", "estimate", "se", "CI_low", "CI_high")],
            file.path(results_dir, paste0(out_prefix, "_eventstudy_bin_contrasts.csv")), row.names = FALSE)
  write.csv(es_pred[, c("Cohort", "Group", "rel_time_bin", "mid", "pred", "lwr", "upr", "vcov_type")],
            file.path(results_dir, paste0(out_prefix, "_eventstudy_predicted_means.csv")), row.names = FALSE)
  write.csv(es_tests, file.path(results_dir, paste0(out_prefix, "_eventstudy_joint_tests.csv")),
            row.names = FALSE)
  write.csv(support, file.path(results_dir, paste0(out_prefix, "_support_by_time_bin.csv")),
            row.names = FALSE)
  write.csv(filter_log, file.path(results_dir, paste0(out_prefix, "_model_filter_log.csv")),
            row.names = FALSE)
  write.csv(censoring_log, file.path(results_dir, paste0(out_prefix, "_own_cancer_censoring_log.csv")),
            row.names = FALSE)
  write.csv(sp_coef, file.path(results_dir, paste0(out_prefix, "_spline_fixed_effects_CI.csv")),
            row.names = FALSE)
  write.csv(sp_pred, file.path(results_dir, paste0(out_prefix, "_spline_predicted_trajectories.csv")),
            row.names = FALSE)
  write.csv(sp_diff, file.path(results_dir, paste0(out_prefix, "_spline_group_difference.csv")),
            row.names = FALSE)
  write.csv(sp_deriv, file.path(results_dir, paste0(out_prefix, "_spline_derivative.csv")),
            row.names = FALSE)
  write.csv(sp_theta, file.path(results_dir, paste0(out_prefix, "_spline_theta.csv")),
            row.names = FALSE)
  write.csv(sp_status, file.path(results_dir, paste0(out_prefix, "_spline_model_status.csv")),
            row.names = FALSE)
  write.csv(convergence_log, file.path(results_dir, paste0(out_prefix, "_convergence_attempts.csv")),
            row.names = FALSE)
  write.csv(variance_components, file.path(results_dir, paste0(out_prefix, "_spline_variance_components.csv")),
            row.names = FALSE)
  write.csv(residual_diagnostics, file.path(results_dir, paste0(out_prefix, "_residual_diagnostics.csv")),
            row.names = FALSE)
  write.csv(random_effect_diagnostics,
            file.path(results_dir, paste0(out_prefix, "_random_effect_diagnostics.csv")), row.names = FALSE)
  write.csv(bounded_diagnostics, file.path(results_dir, paste0(out_prefix, "_spline_bounded_prediction_checks.csv")),
            row.names = FALSE)
  write.csv(spline_omnibus, file.path(results_dir, paste0(out_prefix, "_spline_omnibus_tests.csv")),
            row.names = FALSE)
  write.csv(influence_diagnostics, file.path(results_dir, paste0(out_prefix, "_spline_influence_refits.csv")),
            row.names = FALSE)
  write.csv(spline_scaling, file.path(results_dir, paste0(out_prefix, "_spline_scaling.csv")),
            row.names = FALSE)
  saveRDS(metadata_all, file.path(results_dir, paste0(out_prefix, "_spline_metadata.rds")))
  if (identical(out_prefix, "4.5")) {
    saveRDS(metadata_all[["All Cancer Cohort"]],
            file.path(results_dir, "glme_spline_metadata.rds"))
  }

  cat("\nSaved event-study and spline outputs (prefix '", out_prefix, "') to: ",
      results_dir, "\n", sep = "")
  cat("Saved combined three-page GLME figure PDF to: ", figure_pdf, "\n", sep = "")

  invisible(list(
    es_models = es_models, sp_models = sp_models,
    es_coef = es_coef, es_points = es_points, es_pred = es_pred,
    es_tests = es_tests, sp_coef = sp_coef, sp_pred = sp_pred,
    sp_diff = sp_diff, sp_deriv = sp_deriv, sp_theta = sp_theta, sp_status = sp_status,
    convergence_log = convergence_log, variance_components = variance_components,
    residual_diagnostics = residual_diagnostics,
    random_effect_diagnostics = random_effect_diagnostics,
    bounded_diagnostics = bounded_diagnostics, spline_omnibus = spline_omnibus,
    influence_diagnostics = influence_diagnostics, spline_scaling = spline_scaling,
    matching_provenance = matching_provenance,
    figure_pdf = figure_pdf,
    figures = list(eventstudy = p_event, step = p_step, spline = p_spline)
  ))
}

# Overall-cancer sensitivity grid ---------------------------------------------
# This deliberately fits the prespecified M1 model only. M0--M3 are already
# produced by run_eventstudy_spline_analysis(); each sensitivity changes one
# feature of M1 and writes harmonized, row-bindable outputs.
.filter_two_visit_sensitivity <- function(d) {
  support <- d %>%
    filter(!post_own_cancer, !is.na(fi_score_nocancer), !is.na(Age_Centered)) %>%
    distinct(trajectory_id, cycle) %>%
    count(trajectory_id, name = "n_distinct_fi_dates")
  keep_trajectory <- support$trajectory_id[support$n_distinct_fi_dates >= 2]
  d2 <- d %>% filter(trajectory_id %in% keep_trajectory)
  valid_sets <- d2 %>%
    distinct(matching_id, trajectory_id, Group) %>%
    group_by(matching_id) %>%
    summarize(n_case = sum(Group == "Cancer Case"),
              n_control = sum(Group == "Control"), .groups = "drop") %>%
    filter(n_case == 1, n_control >= 1)
  out <- d2 %>% filter(matching_id %in% valid_sets$matching_id)
  retained_integrity <- out %>%
    distinct(matching_id, trajectory_id, Group) %>%
    group_by(matching_id) %>%
    summarize(n_case = sum(Group == "Cancer Case"),
              n_control = sum(Group == "Control"), .groups = "drop")
  if (any(retained_integrity$n_case != 1 | retained_integrity$n_control < 1)) {
    stop("S12 matched-set integrity failed after the two-visit restriction.")
  }
  retained_visits <- out %>%
    distinct(trajectory_id, cycle) %>%
    count(trajectory_id, name = "n_distinct_fi_dates")
  if (any(retained_visits$n_distinct_fi_dates < 2)) {
    stop("S12 retained a trajectory with fewer than two distinct analytic FI dates.")
  }
  attr(out, "visit_support") <- support
  attr(out, "set_support") <- retained_integrity
  out
}

.fit_one_spline_sensitivity <- function(d, spec, cohort_label = "All Cancer Cohort") {
  required <- c("Group", "id", "matching_id", "trajectory_id", "cycle",
                "Age_Centered", "index_age_z", "base_race", "base_marital",
                "base_living", "post_own_cancer", spec$outcome)
  missing_cols <- setdiff(required, names(d))
  if (length(missing_cols)) stop("missing columns: ", paste(missing_cols, collapse = ", "))

  d <- d %>%
    mutate(Group = factor(Group, levels = c("Control", "Cancer Case")),
           id = factor(id), matching_id = factor(matching_id),
           trajectory_id = factor(trajectory_id), cycle = factor(cycle),
           base_race = factor(base_race), base_marital = factor(base_marital),
           base_living = factor(base_living)) %>%
    filter(!post_own_cancer, !is.na(.data[[spec$outcome]]), !is.na(Age_Centered),
           if_all(all_of(.primary_covars), ~ !is.na(.x))) %>%
    droplevels()
  visit_support <- NULL
  set_support <- NULL
  if (identical(spec$id, "S12")) {
    d <- .filter_two_visit_sensitivity(d)
    visit_support <- attr(d, "visit_support")
    set_support <- attr(d, "set_support")
  }
  if (nrow(d) == 0 || n_distinct(d$Group) < 2) stop("insufficient two-arm support")

  min_case_bin <- if (is.null(spec$min_case_bin)) 50 else spec$min_case_bin
  min_ctrl_bin <- if (is.null(spec$min_ctrl_bin)) 250 else spec$min_ctrl_bin
  support <- add_relative_time_bin(d) %>%
    group_by(rel_time_bin, .drop = FALSE) %>%
    summarize(n_case = n_distinct(id[Group == "Cancer Case"]),
              n_ctrl = n_distinct(id[Group == "Control"]), .groups = "drop") %>%
    mutate(support_ok = n_case >= min_case_bin & n_ctrl >= min_ctrl_bin,
           spec = spec$id)
  supported_window <- continuous_support_window(support, spec$prediction_window)
  if (anyNA(supported_window) || supported_window[[1]] > -spec$prediction_window ||
      supported_window[[2]] < spec$prediction_window) {
    stop("requested +/-", spec$prediction_window,
         " prediction window lacks continuous two-arm support (requires >=",
         min_case_bin, " cases and >=", min_ctrl_bin, " controls per bin)")
  }

  y_name <- spec$outcome
  if (identical(spec$id, "S10")) {
    if (!("n_answered_nocancer" %in% names(d))) {
      stop("n_answered_nocancer is required for S10")
    }
    if (any(d$n_answered_nocancer <= 1, na.rm = TRUE)) {
      stop("S10 requires n_answered_nocancer > 1")
    }
    d <- d %>% mutate(
      .outcome_s10 = qlogis((.data[[y_name]] * (n_answered_nocancer - 1) + 0.5) /
                              n_answered_nocancer)
    )
    y_name <- ".outcome_s10"
  }

  B <- ns(d$Age_Centered, df = spec$spline_df)
  knots <- attr(B, "knots")
  boundary <- attr(B, "Boundary.knots")
  sterms <- paste0("S", seq_len(ncol(B)))
  d <- bind_cols(d, setNames(as.data.frame(B), sterms))
  covars <- .primary_covars
  if (identical(spec$id, "S8")) covars <- c(covars, "cycle")
  rhs <- .fixed_rhs(sterms, covars)
  form <- as.formula(paste(y_name, paste(deparse(rhs), collapse = ""),
                           "+ (1 + Age_Centered | id)"))
  fit_weights <- NULL
  if (identical(spec$id, "S11")) {
    assignment_weights <- d %>%
      distinct(matching_id, trajectory_id, Group) %>%
      group_by(matching_id) %>%
      mutate(n_controls = sum(Group == "Control"),
             match_weight = if_else(Group == "Cancer Case", 1, 1 / n_controls)) %>%
      ungroup() %>% select(matching_id, trajectory_id, match_weight)
    d <- d %>% left_join(assignment_weights, by = c("matching_id", "trajectory_id"))
    fit_weights <- d$match_weight
  }
  fit_info <- .fit_lmer_with_ladder(form, d, paste("sensitivity", spec$id),
                                    weights = fit_weights)
  fit <- fit_info$fit
  Vobj <- get_primary_vcov(fit, d$id, "id")
  beta <- fixef(fit)

  make_grid <- function(t, group) {
    g <- .make_ref_grid(d, covars = covars, Age_Centered = t, Group = group) %>%
      mutate(Group = factor(Group, levels = c("Control", "Cancer Case")))
    bg <- ns(g$Age_Centered, knots = knots, Boundary.knots = boundary)
    bind_cols(g, setNames(as.data.frame(bg), sterms))
  }
  design <- function(t, group) {
    model.matrix(rhs, make_grid(t, group))[, names(beta), drop = FALSE]
  }
  diff_design <- function(t) design(t, "Cancer Case") - design(t, "Control")
  deriv_design <- function(t, h = 1e-4) {
    (diff_design(t + h) - diff_design(t - h)) / (2 * h)
  }
  times <- seq(-spec$prediction_window, spec$prediction_window, by = .25)
  Xc <- design(times, "Cancer Case")
  Xr <- design(times, "Control")
  Xd <- Xc - Xr
  mu_c <- as.vector(Xc %*% beta)
  mu_r <- as.vector(Xr %*% beta)
  est <- as.vector(Xd %*% beta)
  se <- sqrt(rowSums((Xd %*% Vobj$V) * Xd))
  response_diff <- rep(NA_real_, length(times))
  response_se <- rep(NA_real_, length(times))
  response_lwr <- rep(NA_real_, length(times))
  response_upr <- rep(NA_real_, length(times))
  if (identical(spec$id, "S10")) {
    response_diff <- plogis(mu_c) - plogis(mu_r)
    response_gradient <- Xc * (plogis(mu_c) * (1 - plogis(mu_c))) -
      Xr * (plogis(mu_r) * (1 - plogis(mu_r)))
    response_se <- sqrt(rowSums((response_gradient %*% Vobj$V) * response_gradient))
    response_lwr <- response_diff - 1.96 * response_se
    response_upr <- response_diff + 1.96 * response_se
  }
  curve <- data.frame(
    spec = spec$id, Age_Centered = times, estimate = est, se = se,
    lwr = est - 1.96 * se, upr = est + 1.96 * se,
    case_prediction = mu_c, control_prediction = mu_r,
    back_transformed_difference = response_diff,
    back_transformed_se = response_se,
    back_transformed_lwr = response_lwr,
    back_transformed_upr = response_upr,
    vcov_type = Vobj$type
  )

  w <- spec$theta_window
  post <- seq(.025, w - .025, by = .05)
  pre <- seq(-w + .025, -.025, by = .05)
  c_post <- colMeans(do.call(rbind, lapply(post, deriv_design)))
  c_pre <- colMeans(do.call(rbind, lapply(pre, deriv_design)))
  c_theta <- c_post - c_pre
  theta <- as.numeric(c_theta %*% beta)
  theta_closed <- (as.numeric(diff_design(w) %*% beta) -
                     as.numeric(diff_design(0) %*% beta)) / w -
    (as.numeric(diff_design(0) %*% beta) -
       as.numeric(diff_design(-w) %*% beta)) / w
  theta_difference <- theta - theta_closed
  if (!is.finite(theta_difference) || abs(theta_difference) > 1e-6) {
    stop(spec$id, " numerical and closed-form theta differ by more than 1e-6")
  }
  theta_se <- sqrt(as.numeric(t(c_theta) %*% Vobj$V %*% c_theta))
  theta_wald <- wald_with_vcov(fit, Vobj, matrix(c_theta, nrow = 1), "theta")
  theta_df <- theta_wald$df_denom[[1]]
  crit <- if (is.finite(theta_df)) qt(.975, theta_df) else qnorm(.975)
  theta_out <- data.frame(
    spec = spec$id, theta = theta, se = theta_se,
    lwr = theta - crit * theta_se, upr = theta + crit * theta_se,
    p_value = theta_wald$p_value[[1]], df = theta_df,
    pre_window = paste0("[-", w, ",0)"), post_window = paste0("(0,+", w, "]"),
    theta_closed_form = theta_closed,
    theta_closed_form_difference = theta_difference,
    transformed_scale = identical(spec$id, "S10"), vcov_type = Vobj$type,
    rung = fit_info$rung
  )
  status <- data.frame(
    spec = spec$id, status = "fit", n_obs = nrow(d), n_id = n_distinct(d$id),
    n_trajectory_id = n_distinct(d$trajectory_id),
    n_matching_id = n_distinct(d$matching_id),
    fitting_min_time = min(d$Age_Centered), fitting_max_time = max(d$Age_Centered),
    prediction_window = spec$prediction_window, spline_df = spec$spline_df,
    outcome = spec$outcome, rung = fit_info$rung, singular = fit_info$singular,
    convergence = fit_info$converged, optimizer_code = fit_info$optimizer_code,
    scaled_gradient = fit_info$scaled_gradient, vcov_type = Vobj$type,
    message = NA_character_
  )
  list(curve = curve, theta = theta_out, status = status,
       convergence = fit_info$attempts %>% mutate(spec = spec$id, .before = 1),
       variance = .variance_components(fit, cohort_label, spec$id),
       support = support, visit_support = visit_support, set_support = set_support)
}

run_overall_glme_sensitivities <- function(matched_path, exact_cycle_path,
                                           sensitivity_dir) {
  if (!dir.exists(sensitivity_dir)) dir.create(sensitivity_dir, recursive = TRUE)
  base <- readRDS(matched_path)
  if (!("matching_id" %in% names(base))) {
    base <- base %>% mutate(matching_id = paste(Cohort, match_set, sep = "__"))
  }
  if (!("trajectory_id" %in% names(base))) {
    base <- base %>% mutate(trajectory_id = paste(Cohort, match_set, id, role, sep = "__"))
  }
  if (!("index_age" %in% names(base))) {
    stop("Primary matched input is missing index_age; common S7 scaling cannot be verified.")
  }
  primary_case_age <- base %>%
    filter(Group == "Cancer Case") %>%
    distinct(matching_id, index_age)
  if (anyDuplicated(primary_case_age$matching_id)) {
    stop("Primary matched input has more than one case index age per matched set.")
  }
  primary_age_mean <- mean(primary_case_age$index_age, na.rm = TRUE)
  primary_age_sd <- stats::sd(primary_case_age$index_age, na.rm = TRUE)
  if (!is.finite(primary_age_mean) || !is.finite(primary_age_sd) || primary_age_sd <= 0) {
    stop("Primary case-based index-age scaling constants are invalid.")
  }
  specs <- list(
    list(id = "S1", spline_df = 3, prediction_window = 20, theta_window = 8,
         outcome = "fi_score_nocancer", data = base),
    list(id = "S2", spline_df = 5, prediction_window = 20, theta_window = 8,
         outcome = "fi_score_nocancer", data = base),
    list(id = "S3", spline_df = 4, prediction_window = 8, theta_window = 8,
         outcome = "fi_score_nocancer", data = base),
    list(id = "S4", spline_df = 4, prediction_window = 12, theta_window = 8,
         outcome = "fi_score_nocancer", data = base),
    list(id = "S5", spline_df = 4, prediction_window = 20, theta_window = 4,
         outcome = "fi_score_nocancer", data = base),
    list(id = "S6", spline_df = 4, prediction_window = 20, theta_window = 12,
         outcome = "fi_score_nocancer", data = base),
    list(id = "S8", spline_df = 4, prediction_window = 20, theta_window = 8,
         outcome = "fi_score_nocancer", data = base),
    list(id = "S9", spline_df = 4, prediction_window = 20, theta_window = 8,
         outcome = "fi_score_nocancer_nocarry", data = base),
    list(id = "S10", spline_df = 4, prediction_window = 20, theta_window = 8,
         outcome = "fi_score_nocancer", data = base),
    list(id = "S11", spline_df = 4, prediction_window = 20, theta_window = 8,
         outcome = "fi_score_nocancer", data = base),
    list(id = "S12", spline_df = 4, prediction_window = 20, theta_window = 8,
         outcome = "fi_score_nocancer", data = base)
  )
  if (!file.exists(exact_cycle_path)) {
    stop("S7 exact-cycle matched input not found at ", exact_cycle_path)
  }
  exact_provenance <- validate_matching_provenance(exact_cycle_path)
  exact <- readRDS(exact_cycle_path)
  if (!("matching_id" %in% names(exact))) exact <- exact %>% mutate(matching_id = paste(Cohort, match_set, sep = "__"))
  if (!("trajectory_id" %in% names(exact))) exact <- exact %>% mutate(trajectory_id = paste(Cohort, match_set, id, role, sep = "__"))
  if (!("index_age" %in% names(exact))) {
    stop("S7 exact-cycle matched input is missing index_age.")
  }
  exact <- exact %>%
    mutate(index_age_z = (index_age - primary_age_mean) / primary_age_sd)
  specs <- append(specs, list(list(id = "S7", spline_df = 4, prediction_window = 20,
                                  theta_window = 8, outcome = "fi_score_nocancer", data = exact)), after = 6)

  ans <- lapply(specs, function(spec) {
    tryCatch(.fit_one_spline_sensitivity(spec$data, spec), error = function(e) {
      list(curve = NULL, theta = NULL,
           status = data.frame(spec = spec$id, status = "skipped_or_failed",
                               n_obs = NA_integer_, n_id = NA_integer_, n_trajectory_id = NA_integer_,
                               n_matching_id = NA_integer_, fitting_min_time = NA_real_,
                               fitting_max_time = NA_real_, prediction_window = spec$prediction_window,
                               spline_df = spec$spline_df, outcome = spec$outcome,
                               rung = NA_character_, singular = NA, convergence = FALSE,
                               optimizer_code = NA_integer_, scaled_gradient = NA_real_,
                               vcov_type = NA_character_, message = conditionMessage(e)),
           convergence = attr(e, "attempts"), variance = NULL,
           support = NULL, visit_support = NULL, set_support = NULL)
    })
  })
  names(ans) <- vapply(specs, `[[`, character(1), "id")
  write.csv(bind_rows(lapply(ans, `[[`, "curve")),
            file.path(sensitivity_dir, "4.5_sensitivity_difference_curves.csv"), row.names = FALSE)
  write.csv(bind_rows(lapply(ans, `[[`, "theta")),
            file.path(sensitivity_dir, "4.5_sensitivity_theta.csv"), row.names = FALSE)
  write.csv(bind_rows(lapply(ans, `[[`, "status")),
            file.path(sensitivity_dir, "4.5_sensitivity_status.csv"), row.names = FALSE)
  write.csv(bind_rows(lapply(ans, `[[`, "convergence")),
            file.path(sensitivity_dir, "4.5_sensitivity_convergence_attempts.csv"), row.names = FALSE)
  write.csv(bind_rows(lapply(ans, `[[`, "variance")),
            file.path(sensitivity_dir, "4.5_sensitivity_variance_components.csv"), row.names = FALSE)
  write.csv(bind_rows(lapply(ans, `[[`, "support")),
            file.path(sensitivity_dir, "4.5_sensitivity_support_by_time_bin.csv"), row.names = FALSE)
  s12 <- ans[["S12"]]
  if (!is.null(s12$visit_support)) {
    write.csv(s12$visit_support, file.path(sensitivity_dir, "4.5_S12_visit_support.csv"), row.names = FALSE)
    write.csv(s12$set_support, file.path(sensitivity_dir, "4.5_S12_matched_set_support.csv"), row.names = FALSE)
  }
  attr(ans, "exact_cycle_provenance") <- exact_provenance
  invisible(ans)
}

render_overall_glme_html_report <- function(results_dir, sensitivity_dir, visuals_dir,
                                            report_rmd = NULL) {
  if (is.null(report_rmd) || !file.exists(report_rmd)) {
    warning("Overall GLME HTML report skipped because the active R Markdown file is unavailable: ",
            report_rmd, call. = FALSE)
    return(invisible(FALSE))
  }
  if (!dir.exists(visuals_dir)) dir.create(visuals_dir, recursive = TRUE)
  output_html <- file.path(visuals_dir, "4.5_GLME_overall.html")
  ok <- tryCatch({
    if (requireNamespace("rmarkdown", quietly = TRUE) && rmarkdown::pandoc_available()) {
      rmarkdown::render(report_rmd, output_file = basename(output_html),
                        output_dir = visuals_dir, quiet = TRUE,
                        envir = new.env(parent = globalenv()))
    } else {
      if (!requireNamespace("knitr", quietly = TRUE) ||
          !requireNamespace("markdown", quietly = TRUE)) {
        stop("Rendering requires either rmarkdown with Pandoc or both knitr and markdown.")
      }
      knitted_md <- tempfile(fileext = ".md")
      knitr::knit(report_rmd, output = knitted_md, quiet = TRUE,
                  envir = new.env(parent = globalenv()))
      markdown::markdownToHTML(
        knitted_md,
        output = output_html,
        options = c("+embed_resources", "+toc", "+table", "+auto_identifiers"),
        title = "Overall Incident Cancer Risk-Set Matching and GLME"
      )
    }
    if (!file.exists(output_html) || file.info(output_html)$size <= 0) {
      stop("The report renderer did not create a nonempty HTML file.")
    }
    TRUE
  }, error = function(e) {
    warning("Overall GLME HTML report render failed: ", conditionMessage(e), call. = FALSE)
    FALSE
  })
  invisible(ok)
}

