# =============================================================================
# Project: Frailty Trajectories Before and After Incident Cancer in the
#          Health Professionals Follow-up Study
# Script:  10.1_GLME_cancer_free_high_low_burden.R
# Author:  Nemo Zhou
# Date started:      2026-07-19
# Date last updated: 2026-07-19
#
# Purpose:
#   Runs the active 4.0 GLME event-study and natural-spline Gaussian LME model
#   set for the high-burden versus low/moderate-burden cohort generated by the
#   isolated 9.1 cancer-free-through-full-HPFS-endpoint matcher.
#
#   This wrapper does not create or overwrite matching cohorts. It validates the
#   9.xx Gate G4 and MD5 provenance, confirms the endpoint cancer-free flag, and
#   writes model outputs with a unique 10.1 prefix.
#
# Input:
#   Data/riskset_matched_analysis_cancer_free_full_endpoint_long.rds
#     from 9.1_create_cancer_free_high_low_burden.R
#
# Outputs:
#   Event-study and spline CSV summaries under Results/cancer/data with prefix
#   10.1, plus Results/cancer/visuals/10.1_GLME_figures.pdf.
# =============================================================================

project_dir <- "/Users/nemo/Library/CloudStorage/OneDrive-HarvardUniversity/Research/Frailty HPFS"
data_dir    <- file.path(project_dir, "Data")
results_dir <- file.path(project_dir, "Results", "cancer", "data")
visuals_dir <- file.path(project_dir, "Results", "cancer", "visuals")

source(file.path(
  project_dir,
  "Code",
  "2_data_analysis",
  "10.0_GLME_cancer_free_functions.R"
))

run_eventstudy_spline_analysis(
  matched_path = file.path(
    data_dir,
    "riskset_matched_analysis_cancer_free_full_endpoint_long.rds"
  ),
  results_dir = results_dir,
  visuals_dir = visuals_dir,
  out_prefix = "10.1",
  analysis_title =
    "Frailty Event-Study by Cancer Burden (Cancer-Free Through Full HPFS Endpoint)",
  builder_script =
    "Code/2_data_analysis/9.1_create_cancer_free_high_low_burden.R"
)

