# =============================================================================
# Project: Frailty Trajectories Before and After Incident Cancer in the
#          Health Professionals Follow-up Study
# Script:  2.0_riskset_matching_functions.R
# Author:  Nemo Zhou
# Date started:      2026-06-29
# Date last updated: 2026-09-29 (FI-independent matching and complete assignment ledgers)
#
# Purpose:
#   Shared incidence-density risk-set matching utilities used by scripts
#   2.1-2.5. These functions prepare the longitudinal FI panel, classify
#   incident cancer cases into analysis cohorts using precomputed cancer
#   subgroup flags, sample matched controls with replacement from participants
#   already enrolled, alive, cancer-free, and age-calipered at each case index.
#   FI availability and questionnaire recency do not determine entry.
#   Returns the matched long-format analytic data for trajectory scripts.
#
#   This file centralizes risk-set construction so trajectory model scripts do
#   not recreate or overwrite matching cohorts. Downstream scripts should read
#   the datasets generated by 2.1-2.5.
#
# Units:
#   Date variables are months since 1900. Age is calculated as
#   (date - dbmy09) / 12. Age_Centered is years relative to the assigned index.
#   cancer_index_dateca is the canonical earliest cancer date produced by
#   Code/1_data_cleaning/7.4_cancer_subtypes.R; raw cancer_dateca is retained
#   upstream for audit and is not used for analytic timing.
# =============================================================================

library(dplyr)

coalesce0 <- function(x) {
  x <- suppressWarnings(as.numeric(as.character(x)))
  dplyr::coalesce(x, 0)
}

cycle_to_number <- function(x) {
  x_chr <- as.character(x)
  out <- suppressWarnings(as.integer(x_chr))
  # HPFS cycle labels cross the century at "00".  The analytic calendar is
  # 1988, 1992, 1996, 2000, ..., 2020; "00" must therefore map to 2000.
  out <- ifelse(
    !is.na(out) & out >= 0 & out <= 20,
    2000L + out,
    ifelse(!is.na(out) & out >= 80 & out < 100, 1900L + out, out)
  )
  out
}

first_nonmissing <- function(x) {
  x <- x[!is.na(x)]
  if (length(x) == 0) NA else x[[1]]
}

optional_cols <- function(df, cols) {
  intersect(cols, names(df))
}

ensure_optional_cols <- function(df, cols) {
  for (col in cols) {
    if (!col %in% names(df)) df[[col]] <- NA
  }
  df
}

assign_index_cycle <- function(target_cycles, index_date) {
  target_cycles <- as.character(target_cycles)
  target_years <- cycle_to_number(target_cycles)

  if (is.na(index_date) || length(target_cycles) == 0 || anyNA(target_years)) {
    return(list(cycle = NA_character_, rule = "no_cycle"))
  }

  diagnosis_year <- 1900L + floor(as.numeric(index_date) / 12)
  on_or_after <- which(target_years >= diagnosis_year)
  if (length(on_or_after) == 0) {
    return(list(cycle = NA_character_, rule = "no_future_analytic_cycle"))
  }

  idx <- on_or_after[[1]]
  rule <- if (target_years[[idx]] == diagnosis_year) "containing" else "first_after"
  list(cycle = target_cycles[[idx]], rule = rule)
}

latest_observed_cycle_before <- function(obs_dates, obs_cycles, index_date) {
  ok <- !is.na(obs_dates) & obs_dates <= index_date
  if (!any(ok)) {
    return(list(cycle = NA_character_, date = NA_real_))
  }

  pos <- which(ok)
  idx <- pos[which.max(obs_dates[pos])]
  list(cycle = as.character(obs_cycles[[idx]]), date = obs_dates[[idx]])
}

# Only index-time cohort entry, age, survival, and cancer status determine
# control eligibility. This pure helper never inspects FI or future response.
riskset_control_flags <- function(pool, case_id, index_date, case_age, age_caliper) {
  age <- (index_date - pool$dob) / 12
  flags <- data.frame(
    not_self = pool$id != case_id,
    entered = is.finite(pool$first) & pool$first <= index_date,
    alive = is.na(pool$dth) | pool$dth > index_date,
    cancer_free = is.na(pool$canc) | pool$canc > index_date,
    age_ok = is.finite(age) & abs(age - case_age) <= age_caliper)
  flags$eligible <- with(flags, not_self & entered & alive & cancer_free & age_ok)
  flags$eligible[is.na(flags$eligible)] <- FALSE
  flags
}

# Expand already selected assignments; this helper performs no matching.
# A zero-outcome assignment remains in the ledger, not as a phantom FI row.
expand_matched_assignments <- function(assignments, person_level, baseline_covs,
                                      fi_rows, cohort_levels, target_cycles,
                                      index_age_mean, index_age_sd) {
  ledger <- assignments %>%
    left_join(select(person_level, id, dbmy09, dtdth, cancer_dateca,
                     true_age_at_cancer, first_return), by = "id") %>%
    left_join(baseline_covs, by = "id") %>%
    mutate(index_age = (index_date - dbmy09) / 12,
           index_age_z = (index_age - index_age_mean) / index_age_sd,
           Group = if_else(role == "Case", "Cancer Case", "Control"),
           trajectory_id = paste(Cohort, match_set, id, role, sep = "__"),
           matching_id = paste(Cohort, match_set, sep = "__"),
           eligibility_version = "no_fi_requirement_v1",
           own_cancer_after_index = !is.na(cancer_dateca) & cancer_dateca > index_date)
  if (anyDuplicated(ledger$trajectory_id)) stop("Duplicated assignment ledger keys.")
  if (any(!is.finite(ledger$first_return) | ledger$first_return > ledger$index_date))
    stop("Assignment predates analytic-cohort entry.")
  long <- ledger %>%
    inner_join(fi_rows, by = "id", relationship = "many-to-many") %>%
    mutate(Age_Centered = age_at_cycle - index_age,
           Post = if_else(Age_Centered > 0, 1L, 0L),
           Age_Post = if_else(Post == 1L, Age_Centered, 0),
           in_win_8 = abs(Age_Centered) <= 8,
           in_win_12 = abs(Age_Centered) <= 12,
           in_win_16 = abs(Age_Centered) <= 16,
           in_win_20 = abs(Age_Centered) <= 20,
           post_own_cancer = role == "Control" & own_cancer_after_index &
             !is.na(worked_rtmnyr) & worked_rtmnyr >= cancer_dateca)
  if (anyDuplicated(long[c("trajectory_id", "cycle")]))
    stop("Duplicated trajectory_id x cycle rows detected in matched output.")
  if (any(!long$trajectory_id %in% ledger$trajectory_id))
    stop("Outcome row is absent from assignment ledger.")
  availability <- long %>% group_by(trajectory_id) %>% summarize(
    n_analytic_fi_visits = n_distinct(worked_rtmnyr),
    n_uncensored_fi_visits = n_distinct(worked_rtmnyr[!post_own_cancer]),
    n_preindex_fi = n_distinct(worked_rtmnyr[worked_rtmnyr <= index_date]),
    n_postindex_fi = n_distinct(worked_rtmnyr[worked_rtmnyr > index_date]),
    n_recent_preindex_fi = n_distinct(worked_rtmnyr[
      worked_rtmnyr <= index_date & worked_rtmnyr >= index_date - 48]),
    latest_preindex_fi_date = {
      dates <- worked_rtmnyr[worked_rtmnyr <= index_date]
      if (length(dates)) max(dates) else NA_real_
    }, .groups = "drop")
  ledger <- ledger %>% left_join(availability, by = "trajectory_id") %>%
    mutate(across(c(n_analytic_fi_visits, n_uncensored_fi_visits, n_preindex_fi,
                    n_postindex_fi, n_recent_preindex_fi), ~ coalesce(.x, 0L)),
           fi_gap_months = index_date - latest_preindex_fi_date,
           contributes_fi = n_uncensored_fi_visits > 0L)
  long <- long %>% left_join(availability, by = "trajectory_id") %>%
    mutate(fi_gap_months = index_date - latest_preindex_fi_date,
           Cohort = factor(Cohort, levels = cohort_levels),
           Group = factor(Group, levels = c("Control", "Cancer Case")),
           id = factor(id), match_set = factor(match_set),
           role = factor(role, levels = c("Control", "Case")),
           index_cycle = factor(index_cycle, levels = target_cycles))
  set_integrity <- ledger %>% group_by(Cohort, match_set) %>% summarize(
    n_cases = sum(role == "Case"), n_controls = sum(role == "Control"),
    valid_set = n_cases == 1L & n_controls >= 1L, .groups = "drop")
  if (any(!set_integrity$valid_set)) stop("Assignment-ledger matched-set integrity failed.")
  outcome_support <- ledger %>% group_by(Cohort, match_set) %>% summarize(
    n_cases_with_fi = sum(role == "Case" & contributes_fi),
    n_controls_with_fi = sum(role == "Control" & contributes_fi),
    n_assignments_without_fi = sum(!contributes_fi),
    both_arms_with_fi = n_cases_with_fi > 0 & n_controls_with_fi > 0,
    .groups = "drop")
  list(assignments = ledger, matched_long = long,
       set_integrity = set_integrity, outcome_support = outcome_support)
}

prepare_riskset_inputs <- function(input_path,
                                   target_cycles,
                                   classification_vars = character(0)) {
  fi_long <- readRDS(input_path)

  if (!"cancer_index_dateca" %in% names(fi_long)) {
    stop(
      "Missing cancer_index_dateca in input dataset. Run ",
      "Code/1_data_cleaning/7.4_cancer_subtypes.R first.",
      call. = FALSE
    )
  }

  fi_time <- fi_long %>%
    mutate(
      id                = as.character(id),
      cycle             = as.character(cycle),
      cancer_dateca_endpoint = as.numeric(as.character(cancer_dateca)),
      cancer_dateca     = as.numeric(as.character(cancer_index_dateca)),
      dtdth             = as.numeric(as.character(dtdth)),
      dbmy09            = as.numeric(as.character(dbmy09)),
      worked_rtmnyr     = as.numeric(as.character(worked_rtmnyr)),
      date_of_return    = if ("date_of_return" %in% names(.)) date_of_return else NA,
      fi_score_nocancer = as.numeric(as.character(fi_score_nocancer)),
      participated      = as.numeric(as.character(participated)),
      age_at_cancer     = (cancer_dateca - dbmy09) / 12
    )

  if (anyDuplicated(fi_time[c("id", "cycle")]))
    stop("Duplicate participant-cycle records in matching input.")

  missing_class_vars <- setdiff(classification_vars, names(fi_time))
  if (length(missing_class_vars) > 0) {
    stop(
      "Missing cancer classification columns in input dataset: ",
      paste(missing_class_vars, collapse = ", "),
      ". Run Code/1_data_cleaning/7.4_cancer_subtypes.R first."
    )
  }

  if (length(classification_vars) > 0) {
    fi_time <- fi_time %>%
      mutate(across(all_of(classification_vars), coalesce0))

    classification_consistency <- fi_time %>%
      group_by(id) %>%
      summarize(across(all_of(classification_vars), n_distinct), .groups = "drop")
    if (any(as.matrix(classification_consistency[, classification_vars, drop = FALSE]) > 1L)) {
      stop(
        "Cancer classification fields are not constant within participant;",
        " refusing to reconstruct an ever-status from later rows.",
        call. = FALSE
      )
    }
  }

  fi_time <- ensure_optional_cols(
    fi_time,
    c("base_living", "base_calor", "base_sat", "base_diet_chol", "base_nblnk", "base_alco")
  )

  fi_trajectory <- fi_time %>%
    filter(
      participated == 1,
      cycle %in% target_cycles,
      !is.na(fi_score_nocancer),
      is.finite(worked_rtmnyr),
      is.finite(dbmy09)
    ) %>%
    mutate(age_at_cycle = (worked_rtmnyr - dbmy09) / 12) %>%
    arrange(id, age_at_cycle)

  observation_panel <- fi_time %>%
    filter(
      participated == 1,
      cycle %in% target_cycles,
      is.finite(worked_rtmnyr),
      is.finite(dbmy09)
    ) %>%
    mutate(
      observed_raw = TRUE,
      age_at_cycle = (worked_rtmnyr - dbmy09) / 12
    ) %>%
    arrange(id, worked_rtmnyr)

  baseline_covs <- fi_time %>%
    filter(cycle == "86") %>%
    distinct(id, .keep_all = TRUE) %>%
    transmute(
      id,
      base_race    = factor(if_else(is.na(race), "Missing", as.character(race))),
      base_marital = factor(if_else(is.na(marital_status), "Missing", as.character(marital_status))),
      base_living  = factor(if_else(is.na(base_living),
                                    if_else(is.na(living_arr), "Missing", as.character(living_arr)),
                                    as.character(base_living))),
      base_pckgr   = factor(if_else(is.na(pckgr), "Missing", as.character(pckgr))),
      base_calor = as.numeric(as.character(base_calor)),
      base_sat = as.numeric(as.character(base_sat)),
      base_diet_chol = as.numeric(as.character(base_diet_chol)),
      base_nblnk = as.numeric(as.character(base_nblnk)),
      base_alco = as.numeric(as.character(base_alco))
    )

  # Participation, rather than the number or span of FI outcomes over the full
  # record, defines the population that can enter an index-time risk set.
  # FI availability never determines matching eligibility.
  person_level <- observation_panel %>%
    group_by(id) %>%
    arrange(age_at_cycle, .by_group = TRUE) %>%
    summarize(
      dbmy09             = first(dbmy09),
      dtdth              = first(dtdth),
      cancer_dateca      = first(cancer_dateca),
      true_age_at_cancer = first(age_at_cancer),
      base_age           = first(age_at_cycle),
      first_return       = first(worked_rtmnyr),
      last_return        = last(worked_rtmnyr),
      n_visits           = n_distinct(age_at_cycle[!is.na(fi_score_nocancer)]),
      min_age            = min(age_at_cycle),
      max_age            = max(age_at_cycle),
      across(all_of(classification_vars), ~ first(coalesce0(.x))),
      .groups = "drop"
    ) %>%
    mutate(
      age_at_death     = (dtdth - dbmy09) / 12,
      death_status     = if_else(!is.na(dtdth), 1L, 0L),
      is_prevalent     = if_else(!is.na(true_age_at_cancer) & true_age_at_cancer <= base_age, 1L, 0L),
      is_case          = if_else(!is.na(true_age_at_cancer) & true_age_at_cancer >  base_age, 1L, 0L)
    ) %>%
    filter(is_prevalent == 0)

  index_info <- observation_panel %>%
    semi_join(person_level, by = "id") %>%
    group_by(id) %>%
    summarize(
      index_cycle_info = list(assign_index_cycle(target_cycles, first(cancer_dateca))),
      .groups = "drop"
    ) %>%
    mutate(
      index_cycle = vapply(index_cycle_info, `[[`, character(1), "cycle"),
      index_cycle_rule = vapply(index_cycle_info, `[[`, character(1), "rule")
    ) %>%
    select(-index_cycle_info)

  person_level <- person_level %>%
    left_join(index_info, by = "id")

  list(
    fi_trajectory = fi_trajectory,
    observation_panel = observation_panel,
    baseline_covs = baseline_covs,
    person_level = person_level
  )
}

match_one_cohort <- function(case_df,
                             pool,
                             ratio,
                             age_caliper,
                             cohort_label,
                             seed = 20260703) {
  match_case <- function(i) {
    idate <- case_df$cancer_dateca[[i]]
    iage  <- case_df$true_age_at_cancer[[i]]
    cid   <- case_df$id[[i]]
    icyc  <- case_df$index_cycle[[i]]

    age_at_index <- (idate - pool$dob) / 12
    flags <- riskset_control_flags(pool, cid, idate, iage, age_caliper)
    base_idx <- which(flags$eligible)
    cand <- data.frame(id = pool$id[base_idx],
                       control_index_age = age_at_index[base_idx],
                       age_gap = age_at_index[base_idx] - iage,
                       stringsAsFactors = FALSE)
    fail <- with(flags, data.frame(
      match_set = cid, Cohort = cohort_label,
      failed_not_self = sum(!not_self, na.rm = TRUE),
      failed_cohort_entry = sum(not_self & !entered, na.rm = TRUE),
      failed_alive = sum(not_self & entered & !alive, na.rm = TRUE),
      failed_cancer_free = sum(not_self & entered & alive & !cancer_free, na.rm = TRUE),
      failed_age_caliper = sum(not_self & entered & alive & cancer_free & !age_ok, na.rm = TRUE)))
    if (nrow(cand) == 0) {
      return(list(assignment = NULL, n_eligible = 0L, fail = fail))
    }

    # Generate tie-breaking draws from a case-specific seed so parallel
    # execution remains reproducible and independent of worker scheduling.
    set.seed(as.integer((as.double(seed) + i) %% 2147483647))
    picked <- cand %>%
      mutate(tie_break = runif(n())) %>%
      arrange(abs(age_gap), tie_break) %>%
      slice_head(n = min(ratio, nrow(cand))) %>%
      select(-tie_break)

    assignment <- data.frame(
      id = picked$id,
      match_set = cid,
      index_date = idate,
      index_cycle = icyc,
      index_cycle_rule = case_df$index_cycle_rule[[i]],
      donor_case_id = cid,
      riskset_size = nrow(cand),
      age_gap = picked$age_gap,
      role = "Control",
      Cohort = cohort_label,
      stringsAsFactors = FALSE
    )
    list(assignment = assignment, n_eligible = nrow(cand), fail = fail)
  }

  if (nrow(case_df) == 0) {
    case_results <- list()
  } else {
    detected_cores <- parallel::detectCores(logical = FALSE)
    if (is.na(detected_cores)) detected_cores <- 4L
    mc_cores <- min(4L, max(1L, detected_cores - 1L))
    case_results <- parallel::mclapply(
      seq_len(nrow(case_df)),
      match_case,
      mc.preschedule = TRUE,
      mc.cores = mc_cores
    )
  }

  assign_list <- lapply(case_results, `[[`, "assignment")
  n_eligible <- vapply(case_results, `[[`, integer(1), "n_eligible")
  fail_counts <- lapply(case_results, `[[`, "fail")
  controls <- bind_rows(assign_list)
  cases_a <- data.frame(
    id = case_df$id,
    match_set = case_df$id,
    index_date = case_df$cancer_dateca,
    index_cycle = case_df$index_cycle,
    index_cycle_rule = case_df$index_cycle_rule,
    donor_case_id = case_df$id,
    riskset_size = n_eligible,
    age_gap = rep(0, nrow(case_df)),
    role = rep("Case", nrow(case_df)),
    Cohort = rep(cohort_label, nrow(case_df)),
    stringsAsFactors = FALSE
  )

  unmatched_cases <- cases_a %>%
    filter(riskset_size == 0)

  list(
    assignments = bind_rows(
      cases_a %>% filter(riskset_size > 0),
      controls
    ),
    unmatched_cases = unmatched_cases,
    n_eligible = n_eligible,
    fail_counts = bind_rows(fail_counts)
  )
}

build_riskset_matched_long <- function(input_path,
                                       classification_vars,
                                       classify_fn,
                                       cohort_levels,
                                       target_cycles,
                                       match_ratio,
                                       age_caliper,
                                           seed,
                                       index_age_scaling = NULL,
                                       max_unmatched_fraction = 0.10,
                                       max_absolute_smd = 0.05) {
  prepped <- prepare_riskset_inputs(
    input_path = input_path,
    target_cycles = target_cycles,
    classification_vars = classification_vars
  )

  person_level <- prepped$person_level
  person_level$case_cohort <- classify_fn(person_level)

  case_candidates <- person_level %>%
    filter(
      is_case == 1,
      is.finite(true_age_at_cancer),
      !is.na(case_cohort),
      !is.na(index_cycle)
    ) %>%
    arrange(cancer_dateca)

  # No FI or response-recency exclusion is applied to incident case candidates.
  cases <- case_candidates
  inactive_cases <- case_candidates[FALSE, , drop = FALSE]
  inactive_cases$exclusion_reason <- character(0)

  pool <- list(
    id = person_level$id,
    dob = person_level$dbmy09,
    dth = person_level$dtdth,
    canc = person_level$cancer_dateca,
    first = person_level$first_return
  )

  set.seed(seed)
  matched_by_cohort <- lapply(cohort_levels, function(cl) {
    cdf <- cases %>% filter(case_cohort == cl)
    match_one_cohort(
      case_df = cdf,
      pool = pool,
      ratio = match_ratio,
      age_caliper = age_caliper,
      cohort_label = cl,
      seed = seed
    )
  })
  names(matched_by_cohort) <- cohort_levels

  assignments <- bind_rows(lapply(matched_by_cohort, `[[`, "assignments"))
  if (!nrow(assignments)) stop("No eligible matched assignments; no output saved.")
  unmatched_cases <- bind_rows(lapply(matched_by_cohort, `[[`, "unmatched_cases"))

  keep_cols <- c(
    "id", "cycle", "worked_rtmnyr", "age_at_cycle",
    "fi_score", "fi_score_nocancer", "fi_score_nocancer_nocarry",
    "frailty_cat", "frailty_cat_nocancer",
    "n_items_observed", "n_answered", "n_answered_nocancer",
    "items_asked", "items_asked_nocancer"
  )

  fi_keep_cols <- optional_cols(prepped$fi_trajectory, keep_cols)

  fi_rows <- prepped$fi_trajectory %>%
    semi_join(person_level, by = "id") %>%
    select(all_of(fi_keep_cols))

  assignment_ages <- assignments %>%
    left_join(select(person_level, id, dbmy09), by = "id") %>%
    mutate(index_age = (index_date - dbmy09) / 12)
  age_reference <- assignment_ages %>%
    filter(role == "Case") %>%
    distinct(Cohort, match_set, index_age)
  if (is.null(index_age_scaling)) {
    index_age_mean <- mean(age_reference$index_age, na.rm = TRUE)
    index_age_sd <- stats::sd(age_reference$index_age, na.rm = TRUE)
    scaling_source <- "estimated from this matched cohort"
  } else {
    required_scaling <- c("index_age_mean", "index_age_sd")
    missing_scaling <- setdiff(required_scaling, names(index_age_scaling))
    if (length(missing_scaling) > 0) {
      stop("Supplied index_age_scaling is missing: ",
           paste(missing_scaling, collapse = ", "), call. = FALSE)
    }
    index_age_mean <- as.numeric(index_age_scaling$index_age_mean[[1]])
    index_age_sd <- as.numeric(index_age_scaling$index_age_sd[[1]])
    scaling_source <- "reused from primary overall-cancer matched cohort"
  }
  if (!is.finite(index_age_mean) || !is.finite(index_age_sd) || index_age_sd <= 0) {
    stop("Case-based index-age scaling constants are not finite and positive.")
  }
  scaling_metadata <- data.frame(
    reference_population = "one retained cancer case per matched set",
    n_reference_cases = nrow(age_reference),
    index_age_mean = index_age_mean,
    index_age_sd = index_age_sd,
    scaling_source = scaling_source,
    stringsAsFactors = FALSE
  )

  expanded <- expand_matched_assignments(assignments, person_level,
    prepped$baseline_covs, fi_rows, cohort_levels, target_cycles,
    index_age_mean, index_age_sd)
  assignment_ledger <- expanded$assignments
  matched_long <- expanded$matched_long
  set_integrity <- expanded$set_integrity
  caliper_integrity <- assignment_ledger %>% summarize(
    max_abs_age_gap = max(abs(age_gap)),
    all_age_ok = all(abs(age_gap) <= age_caliper),
    all_entry_ok = all(first_return <= index_date), .groups = "drop")
  if (!all(caliper_integrity$all_age_ok, caliper_integrity$all_entry_ok))
    stop("Post-matching age or cohort-entry integrity check failed.")

  diagnostics <- bind_rows(lapply(cohort_levels, function(cl) {
    res <- matched_by_cohort[[cl]]
    data.frame(
      Cohort = cl,
      cases_identified = sum(case_candidates$case_cohort == cl),
      cases_attempted = length(res$n_eligible),
      cases_with_controls = sum(res$n_eligible > 0),
      cases_without_controls = sum(res$n_eligible == 0),
      control_records = sum(res$assignments$role == "Control"),
      distinct_controls = n_distinct(res$assignments$id[res$assignments$role == "Control"]),
        match_ratio = match_ratio,
      age_caliper = age_caliper,
      seed = seed,
      stringsAsFactors = FALSE
    )
  }))

  fail_diagnostics <- bind_rows(lapply(matched_by_cohort, `[[`, "fail_counts"))
  reuse_diagnostics <- assignment_ledger %>%
    filter(role == "Control") %>%
    distinct(Cohort, match_set, id, trajectory_id) %>%
    count(id, name = "control_assignment_count") %>%
    arrange(desc(control_assignment_count))

  post_own_cancer_diagnostics <- matched_long %>%
    filter(role == "Control") %>%
    summarize(
      control_assignments_with_later_own_cancer = sum(assignment_ledger$role == "Control" &
        assignment_ledger$own_cancer_after_index),
      rows_flagged_post_own_cancer = sum(post_own_cancer, na.rm = TRUE),
      .groups = "drop"
    )

  visit_support_diagnostics <- assignment_ledger %>%
    count(Cohort, Group, n_analytic_fi_visits, n_uncensored_fi_visits,
          name = "n_trajectories")

  standardized_difference <- function(x_case, x_control) {
    denom <- sqrt((stats::var(x_case, na.rm = TRUE) + stats::var(x_control, na.rm = TRUE)) / 2)
    if (!is.finite(denom) || denom == 0) return(NA_real_)
    (mean(x_case, na.rm = TRUE) - mean(x_control, na.rm = TRUE)) / denom
  }
  balance_source <- assignment_ages %>%
    mutate(index_cycle_year = cycle_to_number(index_cycle))
  balance_diagnostics <- data.frame(
    variable = c("index_age", "index_cycle_year"),
    absolute_smd = abs(c(
      standardized_difference(balance_source$index_age[balance_source$role == "Case"],
                              balance_source$index_age[balance_source$role == "Control"]),
      standardized_difference(balance_source$index_cycle_year[balance_source$role == "Case"],
                              balance_source$index_cycle_year[balance_source$role == "Control"])
    )),
    stringsAsFactors = FALSE
  )
  gate_status <- diagnostics %>%
    transmute(
      Cohort,
      unmatched_fraction = if_else(cases_attempted > 0,
                                   cases_without_controls / cases_attempted,
                                   0),
      unmatched_ok = unmatched_fraction < max_unmatched_fraction
    ) %>%
    mutate(
      max_absolute_smd_observed = suppressWarnings(max(balance_diagnostics$absolute_smd,
                                                       na.rm = TRUE)),
      balance_ok = all(is.finite(balance_diagnostics$absolute_smd)) &&
        all(balance_diagnostics$absolute_smd < max_absolute_smd),
      gate_pass = unmatched_ok & balance_ok
    )
  if (any(!gate_status$gate_pass)) {
    stop(
      "Gate G4 failed: require unmatched fraction < ", max_unmatched_fraction,
      " and finite absolute SMDs < ", max_absolute_smd, ".",
      call. = FALSE
    )
  }
  run_metadata <- list(
    created_at = format(Sys.time(), tz = "UTC", usetz = TRUE),
    input_path = normalizePath(input_path, mustWork = FALSE),
    input_md5 = unname(tools::md5sum(input_path)),
    target_cycles = target_cycles,
    match_ratio = match_ratio,
    age_caliper_years = age_caliper,
    eligibility_version = "no_fi_requirement_v1",
    fi_requirement = "none",
    cohort_entry_rule = "first_participated_analytic_cycle_return",
    control_entry_on_or_before_index = TRUE,
    max_unmatched_fraction = max_unmatched_fraction,
    max_absolute_smd = max_absolute_smd,
    seed = seed,
    unrestricted_relative_time = TRUE
  )

  list(
    matched_long = matched_long,
    assignments = assignment_ledger,
    outcome_support = expanded$outcome_support,
    diagnostics = diagnostics,
    fail_diagnostics = fail_diagnostics,
    inactive_cases = inactive_cases,
    unmatched_cases = unmatched_cases,
    reuse_diagnostics = reuse_diagnostics,
    post_own_cancer_diagnostics = post_own_cancer_diagnostics,
    visit_support_diagnostics = visit_support_diagnostics,
    set_integrity = set_integrity,
    caliper_integrity = caliper_integrity,
    balance_diagnostics = balance_diagnostics,
    gate_status = gate_status,
    scaling_metadata = scaling_metadata,
    run_metadata = run_metadata
  )
}

save_riskset_match <- function(matched_result, output_path, label) {
  assignment_path <- sub("_long[.]rds$", "_assignments.rds", output_path)
  if (identical(assignment_path, output_path)) stop("Expected a primary *_long.rds output path.")
  saveRDS(matched_result$matched_long, output_path)
  saveRDS(matched_result$assignments, assignment_path)
  diagnostics_dir <- file.path(dirname(dirname(output_path)), "Results", "cancer", "data", "matching_diagnostics")
  if (!dir.exists(diagnostics_dir)) dir.create(diagnostics_dir, recursive = TRUE)
  output_stem <- tools::file_path_sans_ext(basename(output_path))
  write.csv(matched_result$diagnostics,
            file.path(diagnostics_dir, paste0(output_stem, "_yield.csv")),
            row.names = FALSE)
  write.csv(matched_result$fail_diagnostics,
            file.path(diagnostics_dir, paste0(output_stem, "_failed_criteria.csv")),
            row.names = FALSE)
  write.csv(matched_result$inactive_cases,
            file.path(diagnostics_dir, paste0(output_stem, "_inactive_cases.csv")),
            row.names = FALSE)
  write.csv(matched_result$unmatched_cases,
            file.path(diagnostics_dir, paste0(output_stem, "_unmatched_cases.csv")),
            row.names = FALSE)
  write.csv(matched_result$reuse_diagnostics,
            file.path(diagnostics_dir, paste0(output_stem, "_control_reuse.csv")),
            row.names = FALSE)
  write.csv(matched_result$post_own_cancer_diagnostics,
            file.path(diagnostics_dir, paste0(output_stem, "_post_own_cancer.csv")),
            row.names = FALSE)
  write.csv(matched_result$visit_support_diagnostics,
            file.path(diagnostics_dir, paste0(output_stem, "_visit_support.csv")),
            row.names = FALSE)
  write.csv(matched_result$outcome_support,
            file.path(diagnostics_dir, paste0(output_stem, "_outcome_support.csv")), row.names = FALSE)
  write.csv(matched_result$assignments %>% filter(!contributes_fi),
            file.path(diagnostics_dir, paste0(output_stem, "_zero_fi_assignments.csv")), row.names = FALSE)
  write.csv(matched_result$set_integrity,
            file.path(diagnostics_dir, paste0(output_stem, "_set_integrity.csv")),
            row.names = FALSE)
  write.csv(matched_result$caliper_integrity,
            file.path(diagnostics_dir, paste0(output_stem, "_caliper_integrity.csv")),
            row.names = FALSE)
  write.csv(matched_result$balance_diagnostics,
            file.path(diagnostics_dir, paste0(output_stem, "_balance.csv")),
            row.names = FALSE)
  write.csv(matched_result$gate_status,
            file.path(diagnostics_dir, paste0(output_stem, "_gate_g4.csv")),
            row.names = FALSE)
  saveRDS(matched_result$scaling_metadata,
          file.path(diagnostics_dir, paste0(output_stem, "_scaling_metadata.rds")))
  matched_result$run_metadata$output_path <- normalizePath(output_path, mustWork = FALSE)
  matched_result$run_metadata$output_md5 <- unname(tools::md5sum(output_path))
  matched_result$run_metadata$assignment_path <- normalizePath(assignment_path, mustWork = FALSE)
  matched_result$run_metadata$assignment_md5 <- unname(tools::md5sum(assignment_path))
  saveRDS(matched_result$run_metadata,
          file.path(diagnostics_dir, paste0(output_stem, "_run_metadata.rds")))
  saveRDS(
    list(
      scaling = matched_result$scaling_metadata,
      run = matched_result$run_metadata,
      balance = matched_result$balance_diagnostics,
      set_integrity = matched_result$set_integrity,
      caliper_integrity = matched_result$caliper_integrity
    ),
    file.path(diagnostics_dir, paste0(output_stem, "_matching_metadata.rds"))
  )

  cat("\n", label, "\n", sep = "")
  cat("Saved matched dataset to: ", output_path, "\n", sep = "")
  cat("Saved complete assignment ledger to: ", assignment_path, "\n", sep = "")
  cat("Selected assignments: ", nrow(matched_result$assignments), "\n", sep = "")
  cat("Assignments without uncensored FI: ", sum(!matched_result$assignments$contributes_fi), "\n", sep = "")
  cat("Matched analytic rows: ", nrow(matched_result$matched_long), "\n", sep = "")
  print(table(Cohort = matched_result$matched_long$Cohort,
              Group = matched_result$matched_long$Group))
  cat("\nMatching diagnostics:\n")
  print(matched_result$diagnostics)
  cat("\nDiagnostic CSVs written to: ", diagnostics_dir, "\n", sep = "")
}
