# =============================================================================
# Project: Frailty Trajectories Before and After Incident Cancer in the
#          Health Professionals Follow-up Study
# Script:  2.2_create_riskset_smoking_related.R
# Author:  Nemo Zhou
# Date started:      2026-06-29
# Date last updated: 2026-07-18 (symmetric pre-index eligibility and S7 exact-cycle rematch)
#
# Purpose:
#   Creates and overwrites the incidence-density risk-set matched cohort dataset
#   for smoking-related cancer versus cancer-free control trajectory analyses.
#   Smoking-related status is read from the canonical `is_smoking_cancer` flag
#   generated by Code/1_data_cleaning/7.4_cancer_subtypes.R and documented in
#   Documents/Methods/Cancer_Classification.md.
#
# Output:
#   Data/riskset_matched_smoking_long.rds
#   Data/riskset_matched_smoking_exact_cycle_long.rds (S7)
# =============================================================================

library(dplyr)

project_dir <- "/Users/nemo/Library/CloudStorage/OneDrive-HarvardUniversity/Research/Frailty HPFS"
data_dir    <- file.path(project_dir, "Data")
input_path  <- file.path(data_dir, "FI_longitudinal_1986_2020_IMPUTED_Cancer.rds")
output_path <- file.path(data_dir, "riskset_matched_smoking_long.rds")
exact_cycle_output_path <- file.path(data_dir, "riskset_matched_smoking_exact_cycle_long.rds")

source(file.path(project_dir, "Code", "2_data_analysis", "2.0_riskset_matching_functions.R"))

MATCH_RATIO  <- 5
AGE_CALIPER  <- 2
CYCLE_CALIPER <- 1
MIN_VISITS   <- 1
SEED         <- 20260703
target_cycles <- c("88", "92", "96", "00", "04", "08", "12", "16", "20")

cohort_levels <- c("Smoking-Related Cancer Cohort")
classify_fn <- function(pl) {
  ifelse(coalesce0(pl$is_smoking_cancer) == 1,
         "Smoking-Related Cancer Cohort",
         NA_character_)
}

matched_result <- build_riskset_matched_long(
  input_path = input_path,
  classification_vars = "is_smoking_cancer",
  classify_fn = classify_fn,
  cohort_levels = cohort_levels,
  target_cycles = target_cycles,
  match_ratio = MATCH_RATIO,
  age_caliper = AGE_CALIPER,
  cycle_caliper = CYCLE_CALIPER,
  min_visits = MIN_VISITS,
  seed = SEED
)

save_riskset_match(matched_result, output_path, "Smoking-related risk-set cohort")

# S7 exact-cycle rematch; retain the primary case-based age scale.
exact_cycle_result <- build_riskset_matched_long(
  input_path = input_path,
  classification_vars = "is_smoking_cancer",
  classify_fn = classify_fn,
  cohort_levels = cohort_levels,
  target_cycles = target_cycles,
  match_ratio = MATCH_RATIO,
  age_caliper = AGE_CALIPER,
  cycle_caliper = 0,
  min_visits = MIN_VISITS,
  seed = SEED,
  index_age_scaling = matched_result$scaling_metadata
)

save_riskset_match(
  exact_cycle_result,
  exact_cycle_output_path,
  "Smoking-related exact-cycle risk-set cohort (S7)"
)
