# =============================================================================
# Project: Frailty Trajectories Before and After Incident Cancer in the
#          Health Professionals Follow-up Study
# Script:  4.1_diagnose_CR2.R
# Author:  Nemo Zhou
# Date started:      2026-07-22
# Date last updated: 2026-07-22 (moved to Code/tests)
#
# Purpose:
#   Diagnose the CR2 -> CR0 -> model-based covariance fallback for the 4.1
#   primary-adjusted natural-spline LME (M1). This script recreates only the
#   final random-intercept M1 fit for each burden cohort, using the same matched
#   input provenance check, own-cancer censoring, complete-case rule, natural
#   spline basis, and numerical scaling as the shared 4.0 GLME engine.
#
#   For CR2 and CR0 it records the exact outcome of vcovCR(), covariance-matrix
#   validation, coef_test(), and Wald_test(). The participant-id cluster is
#   extracted from model.frame(fit). If it differs from the fitting-data id
#   vector used by the production engine, the script tests that vector too.
#
#   This is a long-running diagnostic refit for Nemo to run manually. It does
#   not rebuild matching and does not overwrite 4.1 result or figure artifacts.
#   Its non-results diagnostic output is Codex/4.1_CR2_diagnosis.csv.
#
# Input:
#   Data/riskset_matched_analysis_long.rds and its Gate G4/provenance records
#   generated by 2.1_create_riskset_high_low_burden.R.
#
# Run manually:
#   Rscript Code/tests/4.1_diagnose_CR2.R
# =============================================================================

project_dir <- "/Users/nemo/Library/CloudStorage/OneDrive-HarvardUniversity/Research/Frailty HPFS"
matched_path <- file.path(project_dir, "Data", "riskset_matched_analysis_long.rds")
diagnostic_dir <- file.path(project_dir, "Codex")
diagnostic_path <- file.path(diagnostic_dir, "4.1_CR2_diagnosis.csv")

source(file.path(project_dir, "Code", "2_data_analysis", "4.0_GLME_spline_functions.R"))

if (!requireNamespace("clubSandwich", quietly = TRUE)) {
  stop("clubSandwich is not installed; CR2/CR0 cannot be diagnosed.", call. = FALSE)
}
if (!dir.exists(diagnostic_dir)) dir.create(diagnostic_dir, recursive = TRUE)

club_sandwich_version <- as.character(utils::packageVersion("clubSandwich"))
diagnostic_rows <- list()

add_row <- function(cohort, fit_status, cr_type = NA_character_,
                    cluster_source = NA_character_, stage, status,
                    message = NA_character_, n_model_rows = NA_integer_,
                    n_model_frame_rows = NA_integer_,
                    n_cluster_values = NA_integer_,
                    n_unique_clusters = NA_integer_,
                    n_missing_clusters = NA_integer_,
                    cluster_matches_model_frame = NA,
                    covariance_nrow = NA_integer_,
                    covariance_ncol = NA_integer_,
                    covariance_finite = NA,
                    covariance_symmetric = NA) {
  diagnostic_rows[[length(diagnostic_rows) + 1L]] <<- data.frame(
    generated_at_utc = format(Sys.time(), tz = "UTC", usetz = TRUE),
    cohort = as.character(cohort),
    model_id = "M1_primary_spline",
    fit_status = fit_status,
    cr_type = cr_type,
    cluster_source = cluster_source,
    stage = stage,
    status = status,
    message = if (is.null(message)) NA_character_ else as.character(message),
    n_model_rows = as.integer(n_model_rows),
    n_model_frame_rows = as.integer(n_model_frame_rows),
    n_cluster_values = as.integer(n_cluster_values),
    n_unique_clusters = as.integer(n_unique_clusters),
    n_missing_clusters = as.integer(n_missing_clusters),
    cluster_matches_model_frame = as.logical(cluster_matches_model_frame),
    covariance_nrow = as.integer(covariance_nrow),
    covariance_ncol = as.integer(covariance_ncol),
    covariance_finite = as.logical(covariance_finite),
    covariance_symmetric = as.logical(covariance_symmetric),
    clubSandwich_version = club_sandwich_version,
    stringsAsFactors = FALSE
  )
}

capture_call <- function(expr) {
  tryCatch(
    list(value = force(expr), error = NA_character_),
    error = function(e) list(value = NULL, error = conditionMessage(e))
  )
}

prepare_m1_data <- function(data) {
  d_spline_basis <- data %>%
    filter(if_all(all_of(.primary_covars), ~ !is.na(.x)))
  spline_bases <- list(
    adjusted_spline = .make_spline_basis(
      d_spline_basis$Age_Centered,
      spline_df = 3L,
      prefix = "S"
    )
  )
  spec <- .trajectory_model_specs$M1_primary_spline
  time_terms <- .model_time_terms(spec, spline_bases)
  d_model <- data %>%
    .add_model_time_terms(spec, spline_bases) %>%
    filter(if_all(all_of(spec$covars), ~ !is.na(.x))) %>%
    droplevels()
  scaling <- .scale_model_numeric_columns(d_model, time_terms)
  fixed_rhs <- .fixed_rhs(spline_terms = time_terms, covars = spec$covars)
  list(
    data = scaling$data,
    formula = update(fixed_rhs, fi_score_nocancer ~ . + (1 | id))
  )
}

diagnose_covariance <- function(fit, cohort, fit_status, d_model) {
  model_frame <- model.frame(fit)
  model_frame_id <- model_frame[["id"]]
  fitting_data_id <- d_model[["id"]]
  clusters_align <- length(model_frame_id) == length(fitting_data_id) &&
    identical(as.character(model_frame_id), as.character(fitting_data_id))

  add_row(
    cohort, fit_status, stage = "cluster_alignment",
    status = if (clusters_align) "success" else "mismatch",
    message = if (clusters_align) NA_character_ else
      "The fitting-data id vector differs from model.frame(fit)$id.",
    n_model_rows = nrow(d_model), n_model_frame_rows = nrow(model_frame),
    n_cluster_values = length(fitting_data_id),
    n_unique_clusters = dplyr::n_distinct(fitting_data_id),
    n_missing_clusters = sum(is.na(fitting_data_id)),
    cluster_matches_model_frame = clusters_align
  )

  cluster_sources <- list(model_frame_id = model_frame_id)
  if (!clusters_align) cluster_sources$fitting_data_id <- fitting_data_id

  for (cluster_source in names(cluster_sources)) {
    cluster <- cluster_sources[[cluster_source]]
    n_unique <- dplyr::n_distinct(cluster)
    n_missing <- sum(is.na(cluster))
    is_model_frame_cluster <- identical(cluster_source, "model_frame_id")

    for (cr_type in c("CR2", "CR0")) {
      vcov_result <- capture_call(
        clubSandwich::vcovCR(fit, cluster = cluster, type = cr_type)
      )
      if (!is.na(vcov_result$error)) {
        add_row(
          cohort, fit_status, cr_type, cluster_source, "vcovCR", "error",
          vcov_result$error, nrow(d_model), nrow(model_frame), length(cluster),
          n_unique, n_missing, is_model_frame_cluster
        )
        next
      }

      V_cs <- vcov_result$value
      V <- as.matrix(V_cs)
      covariance_finite <- all(is.finite(V))
      covariance_symmetric <- isTRUE(all.equal(V, t(V), tolerance = 1e-8))
      covariance_valid <- nrow(V) == length(lme4::fixef(fit)) &&
        ncol(V) == length(lme4::fixef(fit)) &&
        covariance_finite && covariance_symmetric
      add_row(
        cohort, fit_status, cr_type, cluster_source, "covariance_validation",
        if (covariance_valid) "success" else "invalid",
        if (covariance_valid) NA_character_ else
          "Covariance dimensions, finiteness, or symmetry check failed.",
        nrow(d_model), nrow(model_frame), length(cluster), n_unique, n_missing,
        is_model_frame_cluster, nrow(V), ncol(V), covariance_finite,
        covariance_symmetric
      )
      if (!covariance_valid) next

      coefficient_result <- capture_call(
        clubSandwich::coef_test(fit, vcov = V_cs, test = "Satterthwaite")
      )
      add_row(
        cohort, fit_status, cr_type, cluster_source, "coef_test",
        if (is.na(coefficient_result$error)) "success" else "error",
        coefficient_result$error, nrow(d_model), nrow(model_frame),
        length(cluster), n_unique, n_missing, is_model_frame_cluster
      )

      probe <- matrix(0, nrow = 1, ncol = length(lme4::fixef(fit)))
      probe[1, 1] <- 1
      wald_result <- capture_call(
        clubSandwich::Wald_test(fit, constraints = probe, vcov = V_cs,
                                test = "HTZ")
      )
      add_row(
        cohort, fit_status, cr_type, cluster_source, "Wald_test",
        if (is.na(wald_result$error)) "success" else "error",
        wald_result$error, nrow(d_model), nrow(model_frame), length(cluster),
        n_unique, n_missing, is_model_frame_cluster
      )
    }
  }
}

matching_provenance <- validate_matching_provenance(matched_path)
matched_long <- readRDS(matched_path)
needed_cols <- c(
  "Cohort", "Group", "Age_Centered", "index_age_z", "base_race",
  "base_marital", "base_living", "id", "match_set", "role", "cycle",
  "fi_score_nocancer", "post_own_cancer"
)
missing_cols <- setdiff(needed_cols, names(matched_long))
if (length(missing_cols)) {
  stop("Matched dataset is missing required columns: ",
       paste(missing_cols, collapse = ", "), call. = FALSE)
}

if (!("matching_id" %in% names(matched_long))) {
  matched_long$matching_id <- paste(
    matched_long$Cohort, matched_long$match_set, sep = "__"
  )
}
if (!("trajectory_id" %in% names(matched_long))) {
  matched_long$trajectory_id <- paste(
    matched_long$Cohort, matched_long$match_set, matched_long$id,
    matched_long$role, sep = "__"
  )
}

matched_long <- matched_long %>%
  mutate(
    Cohort = droplevels(factor(Cohort)),
    Group = factor(Group, levels = c("Control", "Cancer Case")),
    id = factor(id),
    match_set = factor(match_set),
    matching_id = factor(matching_id),
    trajectory_id = factor(trajectory_id),
    base_race = factor(base_race),
    base_marital = factor(base_marital),
    base_living = factor(base_living)
  ) %>%
  filter(!post_own_cancer, !is.na(fi_score_nocancer), !is.na(Age_Centered)) %>%
  add_relative_time_bin()

if (anyDuplicated(paste(matched_long$trajectory_id, matched_long$cycle, sep = "__"))) {
  stop("Duplicated trajectory_id x cycle rows remain after primary filtering.",
       call. = FALSE)
}

for (cohort in levels(matched_long$Cohort)) {
  d_base <- matched_long %>% filter(Cohort == cohort) %>% droplevels()
  prepared <- capture_call(prepare_m1_data(d_base))
  if (!is.na(prepared$error)) {
    add_row(cohort, "data_preparation_failed", stage = "data_preparation",
            status = "error", message = prepared$error)
    next
  }

  d_model <- prepared$value$data
  fit_warnings <- character()
  fitted <- capture_call(withCallingHandlers(
    lme4::lmer(
      prepared$value$formula,
      data = d_model,
      REML = TRUE,
      control = lme4::lmerControl(
        optimizer = "bobyqa",
        calc.derivs = TRUE,
        optCtrl = list(maxfun = 2e5)
      )
    ),
    warning = function(w) {
      fit_warnings <<- c(fit_warnings, conditionMessage(w))
      invokeRestart("muffleWarning")
    }
  ))
  if (!is.na(fitted$error)) {
    add_row(cohort, "fit_failed", stage = "model_fit", status = "error",
            message = fitted$error, n_model_rows = nrow(d_model))
    next
  }

  fit_check <- .assess_lmer_fit(fitted$value)
  fit_status <- if (isTRUE(fit_check$converged) && !length(fit_warnings)) {
    "accepted"
  } else {
    "not_strictly_accepted"
  }
  fit_message <- paste(c(fit_check$convergence_messages, fit_warnings),
                       collapse = " | ")
  add_row(
    cohort, fit_status, stage = "model_fit", status = "success",
    message = if (nzchar(fit_message)) fit_message else NA_character_,
    n_model_rows = nrow(d_model),
    n_model_frame_rows = nrow(model.frame(fitted$value))
  )
  diagnose_covariance(fitted$value, cohort, fit_status, d_model)
}

diagnostic_table <- dplyr::bind_rows(diagnostic_rows)
utils::write.csv(diagnostic_table, diagnostic_path, row.names = FALSE)

message("CR2/CR0 diagnostic written to ", diagnostic_path)
print(diagnostic_table, row.names = FALSE)
